package local.yiyu.focus;
import okhttp3.*;
import org.json.*;
import org.xmlpull.v1.*;
import java.io.*;
import java.net.URI;
import java.util.*;
import java.util.concurrent.TimeUnit;
import android.util.Base64;
final class Nutstore {
 static final String BASE="https://dav.jianguoyun.com/dav/YiyuFocus/",XML="<?xml version=\"1.0\"?><d:propfind xmlns:d=\"DAV:\"><d:prop><d:getetag/><d:resourcetype/></d:prop></d:propfind>";
 final String username,owner,authorization;private final OkHttpClient http;private final Map<String,String> versions=new HashMap<>(),cachedTags=new HashMap<>();private final Map<String,JSONObject> cache=new HashMap<>();private boolean listed;
 Nutstore(JSONObject credentials)throws Exception{this(credentials,new OkHttpClient.Builder().followRedirects(false).followSslRedirects(false).connectTimeout(15,TimeUnit.SECONDS).readTimeout(15,TimeUnit.SECONDS).callTimeout(20,TimeUnit.SECONDS).build());}
 Nutstore(JSONObject credentials,OkHttpClient transport)throws Exception{http=transport;username=credentials.getString("username").trim().toLowerCase(Locale.ROOT);String password=credentials.getString("password");if(!username.matches("[^\\s@:]+@[^\\s@]+")||username.length()>200||password.isEmpty()||password.length()>500)throw new IOException("请填写坚果云邮箱和应用密码");owner="nutstore:"+username;authorization="Basic "+Base64.encodeToString((username+":"+password).getBytes("UTF-8"),Base64.NO_WRAP);}
 private Response request(String name,String method,String body,Map<String,String> headers)throws Exception{if(!name.isEmpty()&&!"handoff.json".equals(name)&&!name.matches("[a-f0-9-]{36}\\.json"))throw new IOException("同步文件名无效");Request.Builder b=new Request.Builder().url(BASE+name).header("Authorization",authorization);for(Map.Entry<String,String> e:headers.entrySet())b.header(e.getKey(),e.getValue());RequestBody data=body==null?null:RequestBody.create(body,MediaType.parse(headers.getOrDefault("Content-Type","application/json; charset=utf-8")));b.method(method,data);try{return http.newCall(b.build()).execute();}catch(IOException e){throw new IOException("暂时连接不到坚果云。记录仍在本机，联网后可重试。");}}
 private static String text(Response r)throws Exception{if(r.body()==null)return "";if(r.body().contentLength()>8*1024*1024)throw new IOException("云端文件超过 8 MB");return StateStore.text(r.body().byteStream(),8*1024*1024);}
 private static void check(Response r,int... allowed)throws Exception{for(int s:allowed)if(r.code()==s)return;String msg=switch(r.code()){case 401->"账号或应用密码不正确，请用坚果云第三方应用密码";case 403->"坚果云拒绝访问，请检查 WebDAV 授权";case 412->"云端刚有变化，请重新同步，避免覆盖";case 429->"同步请求过于频繁，请稍后重试";case 507->"坚果云空间或流量额度不足";default->"云端暂不可用（"+r.code()+"），本机记录已保留";};throw new IOException(msg);}
 private JSONObject relayDoc;private String relayTag;private boolean relayRead;
 static void validateRelay(JSONObject doc)throws Exception{
  if(doc.optInt("version")!=1||!doc.optString("owner").matches("nutstore:[^\\s@:]+@[^\\s@]+")||!(doc.opt("transfers") instanceof JSONArray)||doc.getJSONArray("transfers").length()>100)throw new IOException("接力记录无效");
  Set<String> ids=new HashSet<>();int offered=0;
  for(int i=0;i<doc.getJSONArray("transfers").length();i++){JSONObject t=doc.getJSONArray("transfers").getJSONObject(i),a=t.getJSONObject("active");String status=t.getString("status");if(!t.getString("id").matches("[a-fA-F0-9-]{36}")||!t.getString("from").matches("[a-fA-F0-9-]{36}")||!ids.add(t.getString("id"))||!Set.of("offered","claimed","cancelled").contains(status)||t.getLong("created")<0||t.getString("label").length()>40||t.getString("position").length()>200||!"focus".equals(a.optString("kind"))||a.optBoolean("running")||a.has("handoffId")||a.getDouble("elapsed")<0||a.getDouble("duration")<1||a.getDouble("duration")>120||a.getDouble("elapsed")>a.getDouble("duration")*60000)throw new IOException("只能接力有效的暂停专注");if(t.has("acknowledged")&&(!(t.get("acknowledged") instanceof Boolean)||"offered".equals(status))||t.has("received")&&(!(t.get("received") instanceof Boolean)||!"claimed".equals(status)))throw new IOException("接力确认格式有误");if("offered".equals(status))offered++;if("claimed".equals(status)&&(!t.getString("to").matches("[a-fA-F0-9-]{36}")||t.getString("to").equals(t.getString("from"))))throw new IOException("接手设备无效");}
  if(offered>1)throw new IOException("已有专注在等待接力");
 }
 JSONObject relayRead()throws Exception{try(Response r=request("handoff.json","GET",null,Map.of())){if(r.code()==404){relayDoc=null;relayTag=null;relayRead=true;return new JSONObject().put("owner",owner).put("etag",JSONObject.NULL).put("doc",JSONObject.NULL);}check(r,200);String tag=r.header("ETag");if(tag==null)throw new IOException("接力缺少版本标识");JSONObject doc=new JSONObject(text(r));validateRelay(doc);if(!owner.equals(doc.getString("owner")))throw new IOException("接力账号不同");relayDoc=doc;relayTag=tag;relayRead=true;return new JSONObject().put("owner",owner).put("etag",tag).put("doc",new JSONObject(doc.toString()));}}
 static boolean same(Object a,Object b)throws Exception{if(a==b)return true;if(a==null||b==null)return false;if(a instanceof JSONObject&&b instanceof JSONObject){JSONObject x=(JSONObject)a,y=(JSONObject)b;if(x.length()!=y.length())return false;Iterator<String> keys=x.keys();while(keys.hasNext()){String k=keys.next();if(!y.has(k)||!same(x.get(k),y.get(k)))return false;}return true;}if(a instanceof JSONArray&&b instanceof JSONArray){JSONArray x=(JSONArray)a,y=(JSONArray)b;if(x.length()!=y.length())return false;for(int i=0;i<x.length();i++)if(!same(x.get(i),y.get(i)))return false;return true;}if(a instanceof Number&&b instanceof Number)return Double.compare(((Number)a).doubleValue(),((Number)b).doubleValue())==0;return a.equals(b);}
 static boolean canPrune(JSONObject t){return t.optBoolean("acknowledged")&&("cancelled".equals(t.optString("status"))||"claimed".equals(t.optString("status"))&&t.optBoolean("received"));}
 static JSONObject byId(JSONObject doc,String id)throws Exception{if(doc==null)return null;JSONArray rows=doc.getJSONArray("transfers");for(int i=0;i<rows.length();i++){JSONObject t=rows.getJSONObject(i);if(id.equals(t.getString("id")))return t;}return null;}
 boolean relayWrite(String device,JSONObject value)throws Exception{
  JSONObject doc=value.getJSONObject("doc");validateRelay(doc);String tag=value.isNull("etag")?null:value.getString("etag");
  if(!relayRead||!Objects.equals(tag,relayTag)||!owner.equals(value.getString("owner"))||!owner.equals(doc.getString("owner"))||tag!=null&&(tag.length()>200||tag.contains("\r")||tag.contains("\n")))throw new IOException("请先刷新接力");
  JSONArray before=relayDoc==null?new JSONArray():relayDoc.getJSONArray("transfers"),after=doc.getJSONArray("transfers");
  for(int i=0;i<before.length();i++){JSONObject old=before.getJSONObject(i),n=byId(doc,old.getString("id"));if(n==null){if(!canPrune(old))throw new IOException("不能移除尚未确认保存的接力");continue;}if(same(old,n))continue;
   JSONObject a=new JSONObject(n.toString());a.put("status",old.getString("status"));a.remove("to");a.remove("acknowledged");a.remove("received");JSONObject b=new JSONObject(old.toString());b.remove("to");b.remove("acknowledged");b.remove("received");
   if(!same(a,b))throw new IOException("不能改变接力内容");
   if(!n.getString("status").equals(old.getString("status"))){if(!"offered".equals(old.getString("status"))||!same(n.opt("acknowledged"),old.opt("acknowledged"))||!same(n.opt("received"),old.opt("received"))||!("cancelled".equals(n.getString("status"))&&device.equals(old.getString("from"))||"claimed".equals(n.getString("status"))&&device.equals(n.optString("to"))&&!device.equals(old.getString("from"))))throw new IOException("接力已变化，请刷新后重试");}
   else if(!same(n.opt("to"),old.opt("to"))||!same(n.opt("acknowledged"),old.opt("acknowledged"))&&!(!"offered".equals(old.getString("status"))&&Boolean.TRUE.equals(n.opt("acknowledged"))&&device.equals(old.getString("from")))||!same(n.opt("received"),old.opt("received"))&&!("claimed".equals(old.getString("status"))&&Boolean.TRUE.equals(n.opt("received"))&&device.equals(old.optString("to"))))throw new IOException("只能确认本机已保存的接力");}
  for(int i=0;i<after.length();i++){JSONObject n=after.getJSONObject(i);if(byId(relayDoc,n.getString("id"))==null&&(!device.equals(n.getString("from"))||!Set.of("offered","cancelled").contains(n.getString("status"))))throw new IOException("只能发送本机专注");}
  String body=doc.toString();if(body.getBytes("UTF-8").length>1024*1024)throw new IOException("接力内容过大");try(Response r=request("handoff.json","PUT",body,Map.of("Content-Type","application/json; charset=utf-8",tag==null?"If-None-Match":"If-Match",tag==null?"*":tag))){check(r,200,201,204);}relayRead=false;return true;
 }
 void connect()throws Exception{try(Response r=request("","MKCOL",null,Map.of())){check(r,201,405);}list();}
 private List<String> list()throws Exception{String xml;try(Response r=request("","PROPFIND",XML,Map.of("Depth","1","Content-Type","application/xml; charset=utf-8"))){check(r,207);xml=text(r);}if(xml.contains("<!DOCTYPE")||xml.contains("<!ENTITY"))throw new IOException("云端目录格式异常");XmlPullParser p=XmlPullParserFactory.newInstance().newPullParser();p.setInput(new StringReader(xml));Map<String,String> next=new HashMap<>();String href="",tag="",status="",propTag="";boolean root=false;int event;
 while((event=p.next())!=XmlPullParser.END_DOCUMENT){String name=p.getName();if(name!=null&&name.contains(":"))name=name.substring(name.indexOf(':')+1);if(event==XmlPullParser.START_TAG){if("multistatus".equals(name))root=true;if("response".equals(name)){href="";tag="";}if("propstat".equals(name)){status="";propTag="";}if("href".equals(name))href=p.nextText();else if("getetag".equals(name))propTag=p.nextText();else if("status".equals(name))status=p.nextText();}else if(event==XmlPullParser.END_TAG){if("propstat".equals(name)&&status.matches(".* 200(?: .*|$)"))tag=propTag;if("response".equals(name)){URI u=URI.create(BASE).resolve(href);String prefix="/dav/YiyuFocus/",n=u.getPath().startsWith(prefix)?u.getPath().substring(prefix.length()):"";if("https".equals(u.getScheme())&&"dav.jianguoyun.com".equals(u.getHost())&&u.getPort()==-1&&n.matches("[a-fA-F0-9-]{36}\\.json")){if(tag.isEmpty())throw new IOException("云端缺少版本标识，已停止同步");next.put(n,tag);}}}}
 if(!root)throw new IOException("云端目录无效");if(next.size()>32)throw new IOException("同步设备文件超过 32 个，请整理 YiyuFocus 文件夹");versions.clear();versions.putAll(next);listed=true;List<String> files=new ArrayList<>(next.keySet());Collections.sort(files);return files;}
 JSONArray read()throws Exception{JSONArray packets=new JSONArray();for(String name:list()){String tag=versions.get(name);JSONObject packet=cache.get(name);if(packet==null||!tag.equals(cachedTags.get(name))){try(Response r=request(name,"GET",null,Map.of())){check(r,200);try{packet=new JSONObject(text(r));}catch(JSONException e){throw new IOException("云端文件损坏，已保留本机记录");}validatePacket(packet);String serverTag=r.header("ETag");cachedTags.put(name,serverTag==null?tag:serverTag);cache.put(name,packet);}}packets.put(new JSONObject(packet.toString()));}cache.keySet().retainAll(versions.keySet());return packets;}
 static void validatePacket(JSONObject packet)throws Exception{if(packet.optInt("version")!=1||!(packet.opt("entries") instanceof JSONArray)||packet.getJSONArray("entries").length()>200000)throw new IOException("云端记录格式不兼容");JSONArray entries=packet.getJSONArray("entries");Set<String> seen=new HashSet<>();for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);String g=e.getString("group"),id=e.getString("id");if(!Set.of("profile","tasks","sessions","thoughts","courseHabits","events","focusPresets").contains(g)||id.length()>100||!seen.add(g+":"+id)||!(e.opt("clock") instanceof JSONObject)||e.getJSONObject("clock").optLong("time",-1)<0||e.getJSONObject("clock").optString("device").isEmpty())throw new IOException("云端记录校验失败");if("profile".equals(g)&&!Set.of("name","motto","goal","duration","breakMinutes","sound").contains(id))throw new IOException("偏好格式错误");if(!"profile".equals(g)&&!e.isNull("value")&&!id.equals(e.getJSONObject("value").optString("id")))throw new IOException("记录标识不一致");}}
 boolean write(String device,JSONObject packet)throws Exception{validatePacket(packet);if(!listed)throw new IOException("请先读取云端，再提交同步");String name=device+".json",body=packet.toString();if(body.getBytes("UTF-8").length>8*1024*1024)throw new IOException("同步文件超过 8 MB，请先导出备份");String previous=versions.get(name);if(previous!=null&&previous.equals(cachedTags.get(name))&&body.equals(String.valueOf(cache.get(name))))return false;Map<String,String> h=new HashMap<>();h.put("Content-Type","application/json; charset=utf-8");h.put(previous==null?"If-None-Match":"If-Match",previous==null?"*":previous);try(Response r=request(name,"PUT",body,h)){check(r,200,201,204);String tag=r.header("ETag");if(tag!=null){versions.put(name,tag);cachedTags.put(name,tag);cache.put(name,new JSONObject(body));}else cache.remove(name);}return true;}
}
