package local.yiyu.focus;
import okhttp3.*;
import org.json.*;
import org.xmlpull.v1.*;
import java.io.*;
import java.net.URI;
import java.util.*;
import java.util.concurrent.TimeUnit;
import android.util.Base64;
final class Nutstore {
 static final String BASE="https://dav.jianguoyun.com/dav/YiyuFocus/",XML="<?xml version=\"1.0\"?><d:propfind xmlns:d=\"DAV:\"><d:prop><d:getetag/><d:resourcetype/></d:prop></d:propfind>";
 final String username,owner,authorization;private final OkHttpClient http;private final Map<String,String> versions=new HashMap<>(),cachedTags=new HashMap<>();private final Map<String,JSONObject> cache=new HashMap<>();private boolean listed;
 Nutstore(JSONObject credentials)throws Exception{this(credentials,new OkHttpClient.Builder().followRedirects(false).followSslRedirects(false).connectTimeout(15,TimeUnit.SECONDS).readTimeout(15,TimeUnit.SECONDS).callTimeout(20,TimeUnit.SECONDS).build());}
 Nutstore(JSONObject credentials,OkHttpClient transport)throws Exception{http=transport;username=credentials.getString("username").trim().toLowerCase(Locale.ROOT);String password=credentials.getString("password");if(!username.matches("[^\\s@:]+@[^\\s@]+")||username.length()>200||password.isEmpty()||password.length()>500)throw new IOException("请填写坚果云邮箱和应用密码");owner="nutstore:"+username;authorization="Basic "+Base64.encodeToString((username+":"+password).getBytes("UTF-8"),Base64.NO_WRAP);}
 private Response request(String name,String method,String body,Map<String,String> headers)throws Exception{if(!name.isEmpty()&&!name.matches("[a-f0-9-]{36}\\.json"))throw new IOException("同步文件名无效");Request.Builder b=new Request.Builder().url(BASE+name).header("Authorization",authorization);for(Map.Entry<String,String> e:headers.entrySet())b.header(e.getKey(),e.getValue());RequestBody data=body==null?null:RequestBody.create(body,MediaType.parse(headers.getOrDefault("Content-Type","application/json; charset=utf-8")));b.method(method,data);try{return http.newCall(b.build()).execute();}catch(IOException e){throw new IOException("暂时连接不到坚果云。记录仍在本机，联网后可重试。");}}
 private static String text(Response r)throws Exception{if(r.body()==null)return "";if(r.body().contentLength()>8*1024*1024)throw new IOException("云端文件超过 8 MB");return StateStore.text(r.body().byteStream(),8*1024*1024);}
 private static void check(Response r,int... allowed)throws Exception{for(int s:allowed)if(r.code()==s)return;String msg=switch(r.code()){case 401->"账号或应用密码不正确，请用坚果云第三方应用密码";case 403->"坚果云拒绝访问，请检查 WebDAV 授权";case 412->"云端刚有变化，请重新同步，避免覆盖";case 429->"同步请求过于频繁，请稍后重试";case 507->"坚果云空间或流量额度不足";default->"云端暂不可用（"+r.code()+"），本机记录已保留";};throw new IOException(msg);}
 void connect()throws Exception{try(Response r=request("","MKCOL",null,Map.of())){check(r,201,405);}list();}
 private List<String> list()throws Exception{String xml;try(Response r=request("","PROPFIND",XML,Map.of("Depth","1","Content-Type","application/xml; charset=utf-8"))){check(r,207);xml=text(r);}if(xml.contains("<!DOCTYPE")||xml.contains("<!ENTITY"))throw new IOException("云端目录格式异常");XmlPullParser p=XmlPullParserFactory.newInstance().newPullParser();p.setInput(new StringReader(xml));Map<String,String> next=new HashMap<>();String href="",tag="",status="",propTag="";boolean root=false;int event;
 while((event=p.next())!=XmlPullParser.END_DOCUMENT){String name=p.getName();if(name!=null&&name.contains(":"))name=name.substring(name.indexOf(':')+1);if(event==XmlPullParser.START_TAG){if("multistatus".equals(name))root=true;if("response".equals(name)){href="";tag="";}if("propstat".equals(name)){status="";propTag="";}if("href".equals(name))href=p.nextText();else if("getetag".equals(name))propTag=p.nextText();else if("status".equals(name))status=p.nextText();}else if(event==XmlPullParser.END_TAG){if("propstat".equals(name)&&status.matches(".* 200(?: .*|$)"))tag=propTag;if("response".equals(name)){URI u=URI.create(BASE).resolve(href);String prefix="/dav/YiyuFocus/",n=u.getPath().startsWith(prefix)?u.getPath().substring(prefix.length()):"";if("https".equals(u.getScheme())&&"dav.jianguoyun.com".equals(u.getHost())&&u.getPort()==-1&&n.matches("[a-fA-F0-9-]{36}\\.json")){if(tag.isEmpty())throw new IOException("云端缺少版本标识，已停止同步");next.put(n,tag);}}}}
 if(!root)throw new IOException("云端目录无效");if(next.size()>32)throw new IOException("同步设备文件超过 32 个，请整理 YiyuFocus 文件夹");versions.clear();versions.putAll(next);listed=true;List<String> files=new ArrayList<>(next.keySet());Collections.sort(files);return files;}
 JSONArray read()throws Exception{JSONArray packets=new JSONArray();for(String name:list()){String tag=versions.get(name);JSONObject packet=cache.get(name);if(packet==null||!tag.equals(cachedTags.get(name))){try(Response r=request(name,"GET",null,Map.of())){check(r,200);try{packet=new JSONObject(text(r));}catch(JSONException e){throw new IOException("云端文件损坏，已保留本机记录");}validatePacket(packet);String serverTag=r.header("ETag");cachedTags.put(name,serverTag==null?tag:serverTag);cache.put(name,packet);}}packets.put(new JSONObject(packet.toString()));}cache.keySet().retainAll(versions.keySet());return packets;}
 static void validatePacket(JSONObject packet)throws Exception{if(packet.optInt("version")!=1||!(packet.opt("entries") instanceof JSONArray)||packet.getJSONArray("entries").length()>200000)throw new IOException("云端记录格式不兼容");JSONArray entries=packet.getJSONArray("entries");Set<String> seen=new HashSet<>();for(int i=0;i<entries.length();i++){JSONObject e=entries.getJSONObject(i);String g=e.getString("group"),id=e.getString("id");if(!Set.of("profile","tasks","sessions","thoughts","courseHabits","events","focusPresets").contains(g)||id.length()>100||!seen.add(g+":"+id)||!(e.opt("clock") instanceof JSONObject)||e.getJSONObject("clock").optLong("time",-1)<0||e.getJSONObject("clock").optString("device").isEmpty())throw new IOException("云端记录校验失败");if("profile".equals(g)&&!Set.of("name","motto","goal","duration","breakMinutes","sound").contains(id))throw new IOException("偏好格式错误");if(!"profile".equals(g)&&!e.isNull("value")&&!id.equals(e.getJSONObject("value").optString("id")))throw new IOException("记录标识不一致");}}
 boolean write(String device,JSONObject packet)throws Exception{validatePacket(packet);if(!listed)throw new IOException("请先读取云端，再提交同步");String name=device+".json",body=packet.toString();if(body.getBytes("UTF-8").length>8*1024*1024)throw new IOException("同步文件超过 8 MB，请先导出备份");String previous=versions.get(name);if(previous!=null&&previous.equals(cachedTags.get(name))&&body.equals(String.valueOf(cache.get(name))))return false;Map<String,String> h=new HashMap<>();h.put("Content-Type","application/json; charset=utf-8");h.put(previous==null?"If-None-Match":"If-Match",previous==null?"*":previous);try(Response r=request(name,"PUT",body,h)){check(r,200,201,204);String tag=r.header("ETag");if(tag!=null){versions.put(name,tag);cachedTags.put(name,tag);cache.put(name,new JSONObject(body));}else cache.remove(name);}return true;}
}
