package local.yiyu.focus;
import android.app.*;
import android.content.*;
import android.os.Build;
import org.json.*;
final class Reminders {
 // Android 15 also sends BOOT_COMPLETED when a stopped package is reopened.
 // Compare boot counters instead of treating every delivery as a device reboot.
 static boolean changedBoot(int previous,int current){return previous>=0&&current>=0&&previous!=current;}
 static JSONObject checkBoot(Context c,StateStore store)throws Exception{int current=android.provider.Settings.Global.getInt(c.getContentResolver(),android.provider.Settings.Global.BOOT_COUNT,-1),previous=c.getSharedPreferences("native",0).getInt("bootCount",-1);JSONObject s=store.load();if(s!=null&&changedBoot(previous,current)){JSONObject a=s.optJSONObject("active");if(a!=null&&a.optBoolean("running")){a.put("running",false);a.put("anchor",System.currentTimeMillis());store.save(s);}}c.getSharedPreferences("native",0).edit().putInt("bootCount",current).apply();return s;}
 static void reschedule(Context c,JSONObject s)throws Exception{c.getSharedPreferences("native",0).edit().remove("deadline").apply();if(s!=null)schedule(c,s);}
 static final String CHANNEL="focus-gentle";static final int TIMER=20,NOTICE=21;
 static void channels(Context c){NotificationManager n=c.getSystemService(NotificationManager.class);n.createNotificationChannel(new NotificationChannel(CHANNEL,"专注与休息提醒",NotificationManager.IMPORTANCE_DEFAULT));n.createNotificationChannel(new NotificationChannel("focus-progress","正在专注",NotificationManager.IMPORTANCE_LOW));}
 static PendingIntent open(Context c){return PendingIntent.getActivity(c,0,new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 static PendingIntent alarm(Context c,String session){return PendingIntent.getBroadcast(c,0,new Intent(c,TimerReceiver.class).putExtra("session",session),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
 static boolean exact(Context c){return Build.VERSION.SDK_INT<31||c.getSystemService(AlarmManager.class).canScheduleExactAlarms();}
 static void schedule(Context c,JSONObject s)throws Exception{channels(c);AlarmManager m=c.getSystemService(AlarmManager.class);NotificationManager n=c.getSystemService(NotificationManager.class);JSONObject a=s.optJSONObject("active");if(a==null||!a.optBoolean("running")||a.optBoolean("waiting")){m.cancel(alarm(c,""));c.getSharedPreferences("native",0).edit().remove("deadline").apply();n.cancel(TIMER);return;}long deadline=a.getLong("anchor")+(long)(a.getDouble("duration")*60000-a.getDouble("elapsed"));if(deadline<=System.currentTimeMillis())return;long previous=c.getSharedPreferences("native",0).getLong("deadline",0);if(previous!=deadline){PendingIntent p=alarm(c,a.getString("id"));try{if(exact(c))m.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,deadline,p);else m.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,deadline,p);}catch(SecurityException e){m.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,deadline,p);}c.getSharedPreferences("native",0).edit().putLong("deadline",deadline).apply();}Notification note=new Notification.Builder(c,"focus-progress").setSmallIcon(R.drawable.ic_leaf).setContentTitle("break".equals(a.optString("kind"))?"休息一下":"一隅 · 正在专注").setContentText(a.optString("title")).setWhen(deadline).setUsesChronometer(true).setChronometerCountDown(true).setOngoing(true).setOnlyAlertOnce(true).setContentIntent(open(c)).build();try{n.notify(TIMER,note);}catch(SecurityException ignored){}}
 static void notify(Context c,String text,boolean arrived){channels(c);NotificationManager n=c.getSystemService(NotificationManager.class);if(arrived)n.cancel(TIMER);long now=System.currentTimeMillis(),last=c.getSharedPreferences("native",0).getLong("lastNotice",0);if(now-last<2000)return;c.getSharedPreferences("native",0).edit().putLong("lastNotice",now).apply();try{n.notify(NOTICE,new Notification.Builder(c,CHANNEL).setSmallIcon(R.drawable.ic_leaf).setContentTitle("一隅 Focus").setContentText(text).setStyle(new Notification.BigTextStyle().bigText(text)).setContentIntent(open(c)).setAutoCancel(true).build());}catch(SecurityException ignored){}}
}
