const {chromium}=require('playwright'),{spawn}=require('child_process'),assert=require('assert/strict'),fs=require('fs/promises');
(async()=>{const server=spawn(process.execPath,['scripts/serve.cjs'],{windowsHide:true,stdio:'pipe'});let browser;try{
 await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject)});browser=await chromium.launch({channel:'msedge',headless:true});await fs.mkdir('test-results',{recursive:true});const errors=[],now=new Date('2026-10-06T12:00:00'),context=await browser.newContext({viewport:{width:1280,height:900}}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:now});await page.goto('http://127.0.0.1:4173');await page.locator('#start').waitFor();
 const read=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('yiyu-focus-v1')));
 await page.locator('[data-page="settings"]').first().click();await page.locator('#auto-zen').check();await page.locator('#celebration-mode').selectOption('confetti');await page.locator('#interface-preferences .primary').click();
 await page.locator('#celebration-preview').click();assert.equal(await page.locator('.completion-confetti').count(),30);await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#celebration-preview').click();assert.equal(await page.locator('.completion-confetti').count(),0);await page.emulateMedia({reducedMotion:'no-preference'});await page.locator('#celebration-mode').selectOption('off');await page.locator('#interface-preferences .primary').click();await page.clock.fastForward(4000);await page.locator('#celebration-preview').click();assert.equal(await page.locator('#completion-feedback').isHidden(),true);
 await page.locator('[data-page="focus"]').first().click();await page.locator('#intention').fill('把第三节读完');await page.locator('#focus-course').fill('模电');await page.locator('#start').click();assert.equal(await page.locator('body').evaluate(e=>e.classList.contains('zen-mode')),true);assert.equal(await page.locator('#intention').isVisible(),false);assert.equal(await page.locator('#zen-target').innerText(),'把第三节读完');await page.screenshot({path:'test-results/immersive-desktop.png'});await page.clock.fastForward(61000);await page.locator('#start').click();const before=(await read()).active.elapsed;await page.clock.fastForward(60000);await page.locator('#start').click();await page.clock.fastForward(3000);await page.locator('#zen').click();assert.equal(await page.locator('#intention').isVisible(),true);await page.locator('#finish').click();await page.locator('#confirm-yes').click();await page.locator('#review-skip').click();assert.ok((await read()).sessions[0].seconds>=Math.floor(before/1000)+3);assert.ok((await read()).sessions[0].seconds<70);assert.ok((await read()).sessions[0].parts);
 await page.locator('[data-page="history"]').first().click();await page.locator('#history-add').click();await page.locator('#record-title').fill('跨午夜补记');await page.locator('#record-course').fill('英语');await page.locator('#record-ended').fill('2026-10-06T00:10');await page.locator('#record-minutes').fill('20');await page.locator('#record-note').fill('记住了新词');await page.locator('#record-editor-form .primary').click();await page.locator('#record-editor').waitFor({state:'hidden'});let s=(await read()).sessions.find(s=>s.title==='跨午夜补记');assert.deepEqual(s.parts,[{day:'2026-10-05',seconds:600},{day:'2026-10-06',seconds:600}]);assert.match(await page.locator('#history-list').innerText(),/手动补记/);const id=s.id;
 await page.locator('[data-edit-time="'+id+'"]').click();await page.locator('#record-minutes').fill('15');await page.locator('#record-editor-form .primary').click();await page.locator('#record-editor').waitFor({state:'hidden'});s=(await read()).sessions.find(s=>s.id===id);assert.equal(s.seconds,900);assert.equal(s.original.seconds,1200);assert.equal(s.corrected,true);assert.equal(await page.locator('#completion-feedback').isHidden(),true);
 await page.locator('[data-page="calendar"]').first().click();await page.locator('#calendar-add').click();await page.locator('#event-title').fill('每日固定阅读');await page.locator('#event-repeat').selectOption('daily');await page.locator('#event-repeat-until').fill('2026-10-09');await page.locator('#event-time').fill('18:00');await page.locator('#event-reminder-anchor').selectOption('start');await page.locator('#event-form .primary').click();await page.locator('#event-dialog').waitFor({state:'hidden'});let rows=(await read()).events;assert.equal(rows.length,4);assert.equal(rows[1].time,'18:00');await page.locator('#calendar-agenda [data-event-done]').click();assert.equal((await read()).events.filter(e=>e.done).length,1);
 await page.locator('#calendar-grid [data-calendar-date="2026-10-07"]').click();await page.locator('#calendar-agenda [data-event-edit]').click();assert.equal(await page.locator('#event-repeat').isDisabled(),true);await page.locator('#event-title').fill('只改这一天');await page.locator('#event-form .primary').click();await page.locator('#event-dialog').waitFor({state:'hidden'});assert.equal((await read()).events.filter(e=>e.title==='只改这一天').length,1);
 await page.locator('#calendar-agenda [data-event-edit]').click();await page.locator('#event-scope').selectOption('future');await page.locator('#event-title').fill('后续固定阅读');await page.locator('#event-repeat-until').fill('2026-10-10');await page.locator('#event-form .primary').click();await page.locator('#event-dialog').waitFor({state:'hidden'});rows=(await read()).events;assert.equal(rows.length,5);assert.equal(rows[0].title,'每日固定阅读');assert.equal(rows[0].done,true);assert.equal(rows.filter(e=>e.title==='后续固定阅读').length,4);
 await page.locator('#calendar-agenda [data-event-delete]').click();await page.locator('#series-delete-one').click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('yiyu-focus-v1')).events.length===4);assert.equal((await read()).trash.length,1);
 await page.locator('#calendar-grid [data-calendar-date="2026-10-08"]').click();await page.locator('#calendar-agenda [data-event-delete]').click();await page.locator('#series-delete-future').click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('yiyu-focus-v1')).events.length===1);assert.equal((await read()).trash.length,4);
 await page.reload();await page.locator('#start').waitFor();assert.equal((await read()).interface.autoZen,true);
 for(const width of [320,360,412,800,1280]){await page.setViewportSize({width,height:900});for(const tab of ['history','calendar','settings']){await page.locator('[data-page="'+tab+'"]:visible').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+tab+' '+width);}await page.locator('[data-page="history"]').first().click();await page.locator('#history-add').click();assert.ok(await page.locator('#record-editor').evaluate(e=>e.getBoundingClientRect().width<=innerWidth));await page.locator('[data-close="record-editor"]').click();await page.locator('[data-page="calendar"]').first().click();await page.locator('#calendar-add').click();await page.locator('#event-repeat').selectOption('weekly');assert.ok(await page.evaluate(()=>document.querySelector('#event-dialog').scrollWidth<=document.querySelector('#event-dialog').clientWidth+1));if(width===412)await page.screenshot({path:'test-results/recurrence-phone.png',animations:'disabled'});await page.locator('[data-close="event-dialog"]').click();}
const celebration=await browser.newPage({viewport:{width:1000,height:900}});const {defaultState,dayKey}=await import('../web/core.mjs');const seed=defaultState();seed.profile.goal=5;seed.profile.duration=1;seed.interface={autoZen:false,celebration:'confetti'};seed.sessions=[{id:'before-goal',title:'先前的专注',seconds:240,ended:+now-1000,day:dayKey(now),completed:true,note:''}];await celebration.clock.install({time:now});await celebration.addInitScript(s=>localStorage.setItem('yiyu-focus-v1',JSON.stringify(s)),seed);await celebration.goto('http://127.0.0.1:4173');await celebration.locator('#intention').fill('完成每日约定');await celebration.locator('#start').click();await celebration.clock.fastForward(61000);await celebration.locator('#soft-finish').click();await celebration.waitForFunction(()=>document.querySelector('#completion-feedback').hidden===false);assert.equal(await celebration.locator('#review-dialog #completion-feedback').count(),1);assert.equal(await celebration.locator('.completion-confetti').count(),30);assert.ok((await celebration.evaluate(()=>JSON.parse(localStorage.getItem('yiyu-focus-v1')))).celebrated.includes('goal:2026-10-06'));await celebration.screenshot({path:'test-results/completion-milestone.png',animations:'disabled'});await celebration.locator('#review-skip').click();await celebration.clock.fastForward(4000);await celebration.locator('#start').click();await celebration.clock.fastForward(61000);await celebration.locator('#soft-finish').click();assert.equal(await celebration.locator('#completion-feedback').isVisible(),false);
 assert.deepEqual(errors,[]);console.log('PASS: immersive focus/pause/exit, optional feedback/reduced motion, manual midnight record/correction, recurring single/future edit and delete, persistent prefs and five responsive sizes.');
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});