const {_electron:electron}=require('playwright');
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises');
(async()=>{
 const root=path.resolve(__dirname,'..'),dataDir=path.join(root,'test-results','floating-'+Date.now());await fs.mkdir(dataDir,{recursive:true});const env={...process.env,YIYU_FOCUS_DATA_DIR:dataDir};delete env.ELECTRON_RUN_AS_NODE;let app;
 const options=process.env.YIYU_TEST_EXE?{executablePath:process.env.YIYU_TEST_EXE,args:[],env}:{args:[root],env};
 try{
  app=await electron.launch(options);const page=await app.firstWindow(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('#start').waitFor();const pref=await page.evaluate(()=>window.desktop.preferences());assert.equal(pref.registrations.capture,true);assert.equal(pref.registrations.floating,true);assert.equal(await app.evaluate(({globalShortcut})=>globalShortcut.isRegistered('Control+Alt+Space')),true);
  await page.locator('#intention').fill('浮窗阅读验证');await page.locator('#focus-course').fill('模电');await page.locator('#custom-minutes').fill('1');await page.locator('#custom-minutes').dispatchEvent('change');await page.locator('#start').click();const created=app.waitForEvent('window');await page.locator('#show-mini').click();const mini=await created;mini.on('pageerror',e=>errors.push(e.message));await mini.locator('#mini-goal').waitFor();assert.equal(await mini.locator('#mini-goal').innerText(),'浮窗阅读验证');assert.equal(await mini.evaluate(()=>typeof window.desktop),'undefined');assert.equal(await mini.evaluate(()=>typeof require),'undefined');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('mini.html')).isAlwaysOnTop()),true);
  await mini.locator('#collapse').click();await mini.waitForFunction(()=>document.body.classList.contains('collapsed'));assert.ok(Math.abs(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('mini.html')).getSize()[1])-54)<=2);await mini.locator('#collapse').click();await mini.locator('#toggle').click();await page.waitForFunction(()=>document.querySelector('#start').textContent.includes('继续'));await mini.locator('#toggle').click();await page.waitForFunction(()=>document.querySelector('#start').textContent.includes('暂停'));await mini.screenshot({path:path.join(root,'test-results/floating-normal.png')});
  const reading=await app.evaluate(async({BrowserWindow})=>{const w=new BrowserWindow({width:600,height:400,title:'隔离阅读验证',webPreferences:{sandbox:true}});await w.loadURL('data:text/html,<h1>Reading test</h1>');w.show();w.focus();return w.id;});await mini.waitForTimeout(400);assert.equal(await app.evaluate(({BrowserWindow},id)=>BrowserWindow.fromId(id).isFocused(),reading),true);
  const previousForeground=await app.evaluate(({app})=>process.getBuiltinModule('module').createRequire(app.getAppPath()+'/package.json')('./desktop/window-focus.cjs').current());await page.evaluate(()=>window.desktop.capture());await mini.locator('#capture-form').waitFor({state:'visible'});await mini.locator('#capture-input').fill('稍后查虚短条件');await mini.screenshot({path:path.join(root,'test-results/floating-capture.png')});await mini.locator('.save').click();await mini.locator('#capture-form').waitFor({state:'hidden'});await mini.waitForTimeout(500);const afterForeground=await app.evaluate(({app})=>process.getBuiltinModule('module').createRequire(app.getAppPath()+'/package.json')('./desktop/window-focus.cjs').current());assert.equal(afterForeground,previousForeground,'Capture should preserve or restore the real Windows foreground window');const data=await page.evaluate(()=>window.desktop.load());assert.equal(data.thoughts[0].text,'稍后查虚短条件');assert.equal(data.thoughts[0].course,'模电');assert.equal(data.thoughts[0].source,'focus');
  await app.evaluate(({BrowserWindow},id)=>BrowserWindow.fromId(id).destroy(),reading);await page.evaluate(async()=>{const data=await window.desktop.load();data.active.elapsed=60000;data.active.anchor=Date.now();await window.desktop.save(data);});await page.reload();await page.locator('#start').waitFor();await page.locator('#start').click();await mini.locator('#mini-soft').waitFor({state:'visible'});assert.equal(await page.locator('#review-dialog').isVisible(),false);await mini.locator('#collapse').click();await mini.locator('#collapse').click();await mini.waitForFunction(()=>innerHeight>=213&&innerHeight<=219);assert.ok(Math.abs(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().find(w=>w.webContents.getURL().endsWith('mini.html')).getSize()[1])-215)<=4);assert.ok(await mini.locator('#extend').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));await mini.screenshot({path:path.join(root,'test-results/floating-soft.png')});await mini.locator('#extend').click();await mini.locator('#mini-soft').waitFor({state:'hidden'});await mini.locator('#finish').click();await page.locator('#confirm-yes').click();await page.locator('#review-skip').click();await page.evaluate(()=>window.prepareToClose());
  await page.locator('[data-page="settings"]').first().click();await page.locator('#backup-now').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('当前记录已备份'));const rows=await page.evaluate(()=>window.desktop.backups());const backup=rows.find(r=>r.reason==='手动备份');assert.ok(backup);assert.equal((await page.evaluate(id=>window.desktop.readBackup(id),backup.id)).sessions.length,1);assert.match(await page.evaluate(()=>window.desktop.openMaterial('C:\\unsafe.exe').then(()=>'',e=>e.message)),/支持/);
  await page.locator('[data-page="focus"]').first().click();await page.locator('#task-input').fill('恢复前新目标');await page.locator('#task-form .add-button').click();await page.evaluate(()=>window.prepareToClose());await page.locator('[data-page="settings"]').first().click();await page.locator('[data-restore-backup="'+backup.id+'"]').click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('备份已恢复'));const restored=await page.evaluate(()=>window.desktop.load());assert.equal(restored.tasks.length,0);assert.equal(restored.sessions.length,1);assert.ok((await page.evaluate(()=>window.desktop.backups())).some(r=>r.reason==='恢复前保护'));await page.screenshot({path:path.join(root,'test-results/workflow-backups.png'),fullPage:true});
  await page.locator('#capture-shortcut').selectOption('off');await page.locator('#floating-shortcut').selectOption('off');await page.locator('#desktop-preferences .primary').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('桌面偏好已保存'));assert.equal(await app.evaluate(({globalShortcut})=>globalShortcut.isRegistered('Control+Alt+Space')),false);assert.deepEqual(errors,[]);
  const closing=app.waitForEvent('close');await page.evaluate(()=>window.close());await closing;app=null;app=await electron.launch(options);const restarted=await app.firstWindow();await restarted.locator('#start').waitFor();assert.equal((await restarted.evaluate(()=>window.desktop.preferences())).capture,'off');assert.equal((await restarted.evaluate(()=>window.desktop.load())).sessions.length,1);await fs.writeFile(path.join(dataDir,'focus-data.json'),'{broken-original');await restarted.reload();await restarted.locator('#save-error').waitFor({state:'visible'});assert.equal(await restarted.locator('#start').isDisabled(),true);await restarted.locator('[data-page="settings"]').first().click();await restarted.locator('#import-file').setInputFiles({name:'safe-backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(restored))});await restarted.locator('#confirm-yes').click();await restarted.waitForFunction(()=>document.querySelector('#toast').textContent.includes('备份已恢复'));assert.equal(await restarted.locator('#start').isDisabled(),false);assert.equal((await restarted.evaluate(()=>window.desktop.load())).sessions.length,1);assert.ok((await fs.readdir(dataDir)).some(name=>name.startsWith('focus-data-corrupt-')));
  console.log('PASS: native always-on-top floating/collapse/timer controls, registered shortcuts, capture persists and preserves/restores the actual Windows foreground handle, mini isolation, soft options, protected backup UI restore, material validation and desktop preference restart.');
 }finally{await app?.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
