import {test} from 'node:test';import assert from 'node:assert/strict';
import {defaultState,dayKey} from '../web/core.mjs';import {growthAnalysis,quantityBuckets} from '../web/growth.mjs';
const now=+new Date('2026-01-03T12:00:00');
const session=(id,ended,patch={})=>({id,title:'学习',ended:+new Date(ended),day:dayKey(new Date(ended)),seconds:600,note:'',completed:true,...patch});
test('local calendar window crosses year, includes midnight, excludes future and old records',()=>{const s=defaultState();s.sessions=[session('a','2025-12-28T00:00:00'),session('b','2025-12-27T23:59:59'),session('c','2026-01-03T12:00:01'),session('d','2026-01-03T12:00:00',{seconds:30})];const a=growthAnalysis(s,{now,period:7});assert.deepEqual(a.days.map(d=>d.day),['2025-12-28','2025-12-29','2025-12-30','2025-12-31','2026-01-01','2026-01-02','2026-01-03']);assert.equal(a.sessions,2);assert.equal(a.seconds,630);assert.equal(a.average,90);assert.equal(a.activeDays,1);assert.equal(a.days.at(-1).seconds,30);});
test('course totals reconcile including uncategorized, filtered charts exclude other courses',()=>{const s=defaultState();s.sessions=[session('a','2026-01-02T10:00:00',{course:' 模电 '}),session('b','2026-01-02T11:00:00',{course:'英语',seconds:300}),session('c','2026-01-03T10:00:00',{seconds:300})];const a=growthAnalysis(s,{now});assert.equal(a.courses.reduce((n,c)=>n+c.seconds,0),a.seconds);assert.equal(a.courses.reduce((n,c)=>n+c.share,0),1);assert.equal(growthAnalysis(s,{now,course:''}).sessions,1);assert.equal(growthAnalysis(s,{now,course:'模电'}).seconds,600);});
test('quantity compares paired entries only, separates units and preserves explicitly recorded zero',()=>{const s=defaultState();s.sessions=[session('a','2026-01-02T10:00:00',{quantity:{target:10,actual:0,unit:'页'}}),session('b','2026-01-02T10:00:00',{quantity:{target:100,unit:'页'}}),session('c','2026-01-02T10:00:00',{quantity:{target:3,actual:5,unit:'题'}})];const a=growthAnalysis(s,{now,period:30}),pages=a.units.find(u=>u.unit==='页');assert.equal(pages.target,10);assert.equal(pages.actual,0);assert.equal(pages.recorded,1);assert.equal(pages.missing,1);assert.equal(a.units.find(u=>u.unit==='题').actual,5);const b=quantityBuckets(pages,30);assert.equal(b.length,5);assert.equal(b.at(-1).to,'2026-01-03');assert.equal(b.reduce((n,r)=>n+r.target,0),10);assert.equal(b.reduce((n,r)=>n+r.count,0),1);});
test('cause proportions count only focus captures, expose missing causes and honor course/time filters',()=>{const s=defaultState();s.thoughts=[{created:now,source:'focus',reason:'phone',course:'模电'},{created:now-1,source:'focus',course:'模电'},{created:now,source:'focus',reason:'phone',course:'英语'},{created:now,source:'inbox',reason:'phone'},{created:now+1,source:'focus',reason:'phone'}];const a=growthAnalysis(s,{now,course:'模电'});assert.equal(a.thoughtCount,2);assert.equal(a.causes.find(c=>c.reason==='unrecorded').count,1);assert.equal(a.causes.reduce((n,c)=>n+c.share,0),1);});
test('empty and invalid period fallback keep meaningful windows without inventing records',()=>{const s=defaultState(),a=growthAnalysis(s,{now,period:123});assert.equal(a.period,30);assert.equal(a.days.length,30);assert.equal(a.sessions,0);assert.equal(a.units.length,0);assert.equal(quantityBuckets(undefined,7).length,0);assert.equal(growthAnalysis(s,{now,period:90}).days.length,90);});
