const {chromium}=require('playwright'),{spawn}=require('child_process'),assert=require('assert/strict'),fs=require('fs/promises');
(async()=>{const server=spawn(process.execPath,['scripts/serve.cjs'],{windowsHide:true,stdio:'pipe'});let browser;try{
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject)});browser=await chromium.launch({channel:'msedge',headless:true});const {defaultState,dayKey}=await import('../web/core.mjs');const state=defaultState(),now=new Date('2026-10-05T15:00:00');
for(let i=0;i<88;i++){const ended=new Date(now);ended.setDate(ended.getDate()-i);ended.setHours(10,0,0,0);if(i%5===3)continue;const course=i%3===0?'模电':i%3===1?'英语':'信号与系统',unit=course==='英语'?'个单词':'页';state.sessions.push({id:'s'+i,title:'练习 '+i,course,seconds:(10+i%6*7)*60,ended:+ended,day:dayKey(ended),completed:i%4!==0,note:'',quantity:{target:course==='英语'?20:5,unit,...(i%6===2?{}:{actual:i%5===0?0:course==='英语'?24:3+i%4})}});state.thoughts.push({id:'t'+i,text:'暂存念头',created:+ended+1000,done:false,source:'focus',course,...(i%7===0?{}:{reason:i%3===0?'phone':i%3===1?'difficult':'tired'})});}
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:now});await page.addInitScript(s=>localStorage.setItem('yiyu-focus-v1',JSON.stringify(s)),state);await page.goto('http://127.0.0.1:4173');await page.locator('#start').waitFor();await page.locator('[data-page="growth"]').first().click();await page.locator('#analysis-trend-svg').waitFor();assert.equal(await page.locator('.analysis-card').count(),4);assert.equal(await page.locator('#analysis-period').inputValue(),'30');assert.equal(await page.locator('#analysis-trend .analysis-data tbody tr').count(),30);await page.locator('#analysis-day-picker').focus();await page.keyboard.press('ArrowLeft');assert.match(await page.locator('#analysis-day-detail').innerText(),/2026-10-04/);await page.locator('#analysis-trend-svg').click({position:{x:46,y:70}});assert.match(await page.locator('#analysis-day-detail').innerText(),/2026-09-06/);
await page.locator('#analysis-period').selectOption('90');assert.equal(await page.locator('#analysis-trend .analysis-data tbody tr').count(),90);assert.equal(await page.locator('#analysis-quantity .analysis-data tbody tr').count(),13);await page.locator('#analysis-period').selectOption('7');assert.equal(await page.locator('#analysis-trend .analysis-data tbody tr').count(),7);assert.equal(await page.locator('#analysis-quantity .analysis-data tbody tr').count(),7);await page.locator('#analysis-unit').selectOption('个单词');assert.match(await page.locator('#analysis-quantity .analysis-metric').innerText(),/个单词/);
await page.locator('[data-analysis-course]').filter({hasText:'模电'}).click();assert.equal(await page.locator('#growth-course').inputValue(),JSON.stringify('模电'));assert.equal(await page.locator('[data-analysis-course]').count(),1);assert.match(await page.locator('#analysis-scope').innerText(),/模电/);assert.match(await page.locator('#analysis-causes').innerText(),/未填写原因/);await page.locator('#analysis-course-reset').click();assert.equal(await page.locator('#growth-course').inputValue(),'all');await page.locator('#growth-course').selectOption(JSON.stringify(''));assert.equal(await page.locator('#analysis-trend-svg').count(),0);assert.match(await page.locator('#analysis-trend').innerText(),/第一段专注/);await page.locator('#growth-course').selectOption('all');await page.locator('#analysis-period').selectOption('30');
await fs.mkdir('test-results',{recursive:true});await page.locator('#growth-analysis').screenshot({path:'test-results/growth-analysis-desktop.png'});
for(const width of [320,360,412,800,1280]){await page.setViewportSize({width,height:width<600?900:1100});await page.locator('#analysis-period').selectOption('90');await page.waitForTimeout(180);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow '+width);const plots=await page.locator('.analysis-plot').evaluateAll(nodes=>nodes.map(e=>({rendered:e.getBoundingClientRect().width,view:e.viewBox.baseVal.width,text:e.querySelector('text').getBoundingClientRect().height})));for(const p of plots){assert.ok(Math.abs(p.rendered-p.view)<2,'plot must use native label scale');assert.ok(p.text>=10,'labels readable');}await page.locator('#analysis-trend .analysis-data summary').click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('#analysis-trend .analysis-data summary').click();if(width===412)await page.locator('#growth-analysis').screenshot({path:'test-results/growth-analysis-phone.png'});if(width===1280)await page.locator('#growth-analysis').screenshot({path:'test-results/growth-analysis-tablet.png'});}
assert.deepEqual(errors,[]);const emptyPage=await browser.newPage({viewport:{width:360,height:800}});await emptyPage.goto('http://127.0.0.1:4173');await emptyPage.locator('#start').waitFor();await emptyPage.locator('[data-page="growth"]').first().click();assert.equal(await emptyPage.locator('.analysis-empty').count(),4);assert.equal(await emptyPage.locator('#analysis-unit').isDisabled(),true);const tiny=defaultState();tiny.sessions=[{id:'tiny',title:'少量学习',course:'',seconds:1,ended:+now,day:dayKey(now),completed:false,note:'',quantity:{target:0.001,actual:0,unit:'章'}}];const tinyPage=await browser.newPage({viewport:{width:320,height:800}});await tinyPage.clock.install({time:now});await tinyPage.addInitScript(s=>localStorage.setItem('yiyu-focus-v1',JSON.stringify(s)),tiny);await tinyPage.goto('http://127.0.0.1:4173');await tinyPage.locator('#start').waitFor();await tinyPage.locator('[data-page="growth"]').first().click();assert.match(await tinyPage.locator('#analysis-quantity .analysis-metric').innerText(),/0.001/);assert.ok((await tinyPage.locator('#analysis-quantity-svg text').allTextContents()).includes('0.001'));assert.ok(await tinyPage.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
console.log('PASS: growth range/course/unit filters, missing and zero data, pointer/touch-compatible/keyboard controls, data tables, five responsive sizes and native label sizing; test records isolated from user data.');
}finally{await browser?.close();server.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
