const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{spawn}=require('node:child_process');
(async()=>{
 const {defaultState,dayKey}=await import('../web/core.mjs');const seed=defaultState(),now=Date.now();seed.profile.name='学习流程预览';seed.profile.motto='隔离测试数据，用于验证新功能。';
 const session=(id,title,days,seconds,extra={})=>{const date=new Date(now);date.setDate(date.getDate()-days);date.setHours(9,0,0,0);if(days===0)date.setTime(now-600000);return {id,title,note:'',seconds,ended:date.getTime(),day:dayKey(date),completed:true,...extra};};
 seed.sessions=[session('legacy','旧版记录',9,1000,{note:'旧笔记完整保留'}),session('english','读英语课文',1,1200,{course:'英语',note:'记住了三个表达'}),session('unsafe','<img src=x onerror=alert(1)>',1,180,{course:'<svg/onload=alert(1)>',note:'<script>alert(1)</script>'}),session('last','读第 3 节',0,900,{course:'模电',note:'理解了负反馈',nextStep:'做第一道题'})];
 const server=spawn(process.execPath,[path.join(__dirname,'../scripts/serve.cjs')],{windowsHide:true,stdio:'pipe'});let browser;
 try{
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('Server exited '+code)));});
  browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1280,height:960},acceptDownloads:true}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  await context.addInitScript(data=>{if(!localStorage.getItem('yiyu-focus-v1'))localStorage.setItem('yiyu-focus-v1',JSON.stringify(data));},seed);
  await page.goto('http://127.0.0.1:4173');await page.locator('#quick-resume').waitFor();
  assert.equal(await page.locator('#intention').inputValue(),'做第一道题');assert.equal(await page.locator('#focus-course').inputValue(),'模电');
  await page.clock.install();await page.locator('#quick-resume').click();assert.equal(await page.locator('#timer').innerText(),'05:00');assert.equal(await page.locator('#focus-course').isDisabled(),true);
  for(let i=0;i<2;i++){await page.locator('#distracted').click();assert.equal(await page.locator('#return-target').innerText(),'做第一道题');await page.locator('#distraction-input').fill('想查车票');await page.locator('#distraction-form .primary').click();}
  await page.clock.fastForward(301000);await page.locator('#soft-finish').click();await page.locator('#review-dialog').waitFor({state:'visible'});await page.locator('#review-note').fill('理解了第一题的反馈路径');await page.locator('#review-next-step').fill('从第 18 页继续');await page.locator('#review-skip').click();
  await page.reload();assert.equal(await page.locator('#intention').inputValue(),'从第 18 页继续');assert.equal(await page.locator('#resume-target').innerText(),'从第 18 页继续');
  let stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('yiyu-focus-v1')));assert.equal(stored.sessions.length,5);assert.equal(stored.sessions[4].seconds,300);assert.equal(stored.sessions[4].course,'模电');assert.equal(stored.thoughts[0].source,'focus');assert.equal(stored.thoughts[0].sessionId,stored.sessions[4].id);
  await page.locator('[data-page="growth"]').first().click();const today=dayKey(now);await page.locator('[data-day="'+today+'"]').click();assert.match(await page.locator('#day-summary').innerText(),/2 次专注/);assert.match(await page.locator('#day-records').innerText(),/理解了第一题的反馈路径/);
  await page.locator('#day-records [data-edit-note]').first().click();assert.equal(await page.locator('#review-submit').innerText(),'保存修改');await page.locator('#review-course').fill('信号与系统');await page.locator('#review-submit').click();
  assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('yiyu-focus-v1')).active),null);assert.match(await page.locator('#day-records').innerText(),/信号与系统/);await page.locator('#detail-date').fill(seed.sessions[0].day);await page.locator('#detail-date').dispatchEvent('change');assert.match(await page.locator('#day-records').innerText(),/旧笔记完整保留/);await page.locator('[data-close="day-dialog"]').click();
  await page.locator('#growth-course').selectOption(JSON.stringify('模电'));await page.locator('[data-day="'+today+'"]').click();assert.match(await page.locator('#day-summary').innerText(),/1 次专注 · 15 分钟/);await page.locator('[data-close="day-dialog"]').click();
  await page.locator('#growth-course').selectOption('all');assert.match(await page.locator('#week-thoughts').innerText(),/想查车票/);assert.match(await page.locator('#week-thoughts').innerText(),/2 次暂存/);assert.equal(await page.locator('#week-notes script').count(),0);
  await page.locator('[data-page="history"]').first().click();await page.locator('#history-course').selectOption(JSON.stringify(''));assert.equal(await page.locator('#history-list .record').count(),1);assert.match(await page.locator('#history-list').innerText(),/旧笔记完整保留/);
  await page.locator('#history-list [data-edit-note]').click();await page.locator('#review-course').fill('模电');await page.locator('#review-submit').click();assert.equal(await page.locator('#history-list .record').count(),0);await page.locator('#history-course').selectOption('all');assert.equal(await page.locator('#history-list .record').count(),5);assert.equal(await page.locator('#history-list img, #history-list script, #history-list svg').count(),0);
  await page.locator('[data-page="growth"]').first().click();await page.locator('#course-period').selectOption('all');assert.match(await page.locator('#course-totals').innerText(),/模电/);
  await fs.mkdir(path.join(__dirname,'../test-results'),{recursive:true});await page.screenshot({path:path.join(__dirname,'../test-results/learning-growth.png'),fullPage:true,animations:'disabled'});
  await page.locator('#week-plan-title').fill('读第 4 节的前两页');await page.locator('#week-plan-course').fill('英语');await page.locator('#week-plan-form .primary').click();assert.equal(await page.locator('#intention').inputValue(),'读第 4 节的前两页');assert.equal(await page.locator('#focus-course').inputValue(),'英语');assert.match(await page.locator('#task-list').innerText(),/读第 4 节/);
  await page.screenshot({path:path.join(__dirname,'../test-results/learning-focus.png'),fullPage:true,animations:'disabled'});
  await page.locator('#quick-resume').click();assert.equal(await page.locator('#timer').innerText(),'05:00');await page.clock.fastForward(2000);await page.locator('#start').click();const remaining=await page.locator('#timer').innerText();await page.reload();await page.locator('#quick-resume').click();assert.equal(await page.locator('#timer').innerText(),remaining);
  await page.locator('#finish').click();await page.locator('#confirm-yes').click();await page.locator('#review-skip').click();
  await page.locator('#intention').fill('');await page.waitForTimeout(500);await page.reload();assert.equal(await page.locator('#intention').inputValue(),'');await page.locator('#intention').fill('尚未开始的草稿');await page.locator('#focus-course').fill('数学');await page.waitForTimeout(500);await page.reload();assert.equal(await page.locator('#intention').inputValue(),'尚未开始的草稿');assert.equal(await page.locator('#focus-course').inputValue(),'数学');
  await page.setViewportSize({width:390,height:844});await page.locator('[data-page="growth"]').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'../test-results/learning-mobile.png'),fullPage:true,animations:'disabled'});
  await page.locator('[data-day="'+today+'"]').click();assert.ok(await page.locator('#day-dialog').evaluate(el=>el.getBoundingClientRect().width<=innerWidth));await page.locator('[data-close="day-dialog"]').click();
  await page.locator('#mobile-settings').click();const event=page.waitForEvent('download');await page.locator('#export').click();const downloaded=await event,backup=JSON.parse(await fs.readFile(await downloaded.path(),'utf8'));assert.equal(backup.sessions.length,6);assert.equal(backup.sessions.find(s=>s.id==='legacy').course,'模电');assert.equal(backup.sessions[4].nextStep,'从第 18 页继续');
  await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))});await page.locator('#confirm-yes').click();await page.locator('[data-page="history"]').first().click();assert.equal(await page.locator('#history-list .record').count(),6);assert.deepEqual(errors,[]);
  console.log('PASS: quick five-minute recovery, paused-timer continuation, next-step/draft reload, captured distraction grouping, daily detail and editing without rest, course filtering/reclassification, safe text, weekly planning, mobile layout and old/new backup round-trip.');
 }finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
