import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultState,validateState,dayKey} from '../web/core.mjs';
import {validDate,monthDays,shiftMonth,eventsOnDay,deadlineLabel,quantityTotals} from '../web/planning.mjs';
import {SyncTracker} from '../web/sync.mjs';
import {recycle,recover} from '../web/workflow.mjs';
const event=(id='event')=>({id,title:'交实验报告',icon:'🧪',date:'2026-10-05',endDate:'2026-10-07',time:'',endTime:'',deadline:'2026-10-08T23:59',course:'模电',notes:'附上数据表',done:false,created:1,updated:1});
test('calendar uses real local dates, Monday weeks, leap years and year boundaries',()=>{assert.equal(validDate('2026-02-30'),false);assert.equal(validDate('2024-02-29'),true);assert.equal(validDate('2025-02-29'),false);assert.equal(validDate('2026-10-05junk'),false);const days=monthDays('2026-10');assert.equal(days.length,42);assert.equal(days[0],'2026-09-28');assert.equal(new Set(days).size,42);assert.equal(shiftMonth('2026-12',1),'2027-01');assert.equal(shiftMonth('2026-01',-1),'2025-12');});
test('spanning events appear on all scheduled days and their separate DDL date',()=>{const e=event();assert.equal(eventsOnDay([e],'2026-10-06').length,1);assert.equal(eventsOnDay([e],'2026-10-08').length,1);assert.equal(eventsOnDay([e],'2026-10-09').length,0);assert.equal(deadlineLabel(e,+new Date('2026-10-08T23:30')),'距 DDL 29 分钟');assert.equal(deadlineLabel(e,+new Date('2026-10-09T00:00')),'已过截止时间');assert.equal(deadlineLabel({...e,done:true}),'已完成');});
test('legacy backups stay valid; malformed calendar and quantity data are rejected',()=>{const old=defaultState();delete old.events;assert.equal(validateState(old),old);const s=defaultState();s.events=[event()];s.tasks=[{id:'task',title:'读三页',done:false,quantity:{target:3,unit:'页'}}];assert.doesNotThrow(()=>validateState(s));for(const change of [{date:'2026-02-30'},{endDate:'2026-10-04'},{time:'25:00'},{endTime:'15:00'},{time:'15:00',endTime:'14:00',endDate:'2026-10-05'},{deadline:'2026-10-08T24:00'},{icon:'<script>'}])assert.throws(()=>validateState({...s,events:[{...event(),...change}]}));for(const q of [{target:0,unit:'页'},{target:3,unit:''},{target:3,unit:'页',actual:-1}])assert.throws(()=>validateState({...s,tasks:[{...s.tasks[0],quantity:q}]}));});
test('actual learning totals never infer completion and keep incompatible units separate',()=>{assert.deepEqual(quantityTotals([{quantity:{target:3,unit:'页'}},{quantity:{target:3,unit:'页',actual:2}},{quantity:{target:5,unit:'题',actual:0}},{quantity:{target:1,unit:'页',actual:0.5}}]),[{unit:'页',actual:2.5},{unit:'题',actual:0}]);});
test('calendar changes, learning amount, deletions and recovery converge across devices',()=>{const a=defaultState(),b=defaultState();a.events=[event()];const ended=Date.now();a.sessions=[{id:'study',title:'读三页',note:'',seconds:60,ended,day:dayKey(ended),completed:true,quantity:{target:3,unit:'页',actual:2}}];const x=new SyncTracker(a,'win'),y=new SyncTracker(b,'android');y.merge([x.packet()]);let current=y.apply(b);assert.equal(current.events[0].icon,'🧪');assert.equal(current.sessions[0].quantity.actual,2);current.events[0].done=true;y.observe(current);x.merge([y.packet()]);let win=x.apply(a);assert.equal(win.events[0].done,true);recycle(win,'events','event');x.observe(win);y.merge([x.packet()]);assert.equal(y.apply(current).events.length,0);recover(win,win.trash[0].id);x.observe(win);y.merge([x.packet()]);assert.deepEqual(y.apply(current).events,win.events);assert.doesNotThrow(()=>validateState(JSON.parse(JSON.stringify(win))));});

const preset=()=>({id:'preset',title:'背单词',icon:'📚',minutes:10,course:'英语',quantity:{target:20,unit:'个单词'},created:1,updated:1});
test('fixed focus presets accept legacy backups and reject malformed durations, goals and duplicate IDs',()=>{const old=defaultState();delete old.focusPresets;assert.doesNotThrow(()=>validateState(old));const state={...defaultState(),focusPresets:[preset()]};assert.doesNotThrow(()=>validateState(JSON.parse(JSON.stringify(state))));for(const fields of [{minutes:0},{minutes:121},{minutes:1.5},{title:' '},{icon:'unsafe'},{quantity:{target:20,unit:'个单词',actual:2}}])assert.throws(()=>validateState({...state,focusPresets:[{...preset(),...fields}]}));assert.throws(()=>validateState({...state,focusPresets:[preset(),preset()]}));});
test('fixed events merge across devices, preserve local running work, and support synced deletion and restore',()=>{const a=defaultState(),b=defaultState();a.focusPresets=[preset()];const x=new SyncTracker(a,'win'),y=new SyncTracker(b,'phone');y.merge([x.packet()]);const active={id:'local',title:'另一段学习',kind:'focus',duration:15,elapsed:0,anchor:Date.now(),running:true};let phone=y.apply({...b,active});assert.equal(phone.focusPresets[0].minutes,10);assert.deepEqual(phone.active,active);phone.focusPresets[0].minutes=25;y.observe(phone);x.merge([y.packet()]);let win=x.apply(a);assert.equal(win.focusPresets[0].minutes,25);recycle(win,'focusPresets','preset');x.observe(win);y.merge([x.packet()]);assert.equal(y.apply(phone).focusPresets.length,0);recover(win,win.trash[0].id);x.observe(win);y.merge([x.packet()]);assert.equal(y.apply(phone).focusPresets[0].quantity.target,20);});
