const {chromium}=require('playwright');
const {spawn}=require('node:child_process');
const fs=require('node:fs/promises'),path=require('node:path'),net=require('node:net'),assert=require('node:assert/strict');
(async()=>{
  const root=path.resolve(__dirname,'..'),dataDir=path.join(root,'test-results','portable-'+Date.now());await fs.mkdir(dataDir,{recursive:true});
  const port=await new Promise(resolve=>{const server=net.createServer();server.listen(0,'127.0.0.1',()=>{const p=server.address().port;server.close(()=>resolve(p));});});
  const env={...process.env,YIYU_FOCUS_DATA_DIR:dataDir};delete env.ELECTRON_RUN_AS_NODE;
  const version=require('../package.json').version;
  const proc=spawn(path.join(root,`release/Yiyu-Focus-${version}-Windows.exe`),[`--remote-debugging-port=${port}`],{env,windowsHide:true,stdio:'ignore'});let browser;
  try{
    let ready=false;for(let i=0;i<120;i++){try{const r=await fetch(`http://127.0.0.1:${port}/json/version`);if(r.ok){ready=true;break;}}catch{}await new Promise(r=>setTimeout(r,250));}assert.ok(ready,'Portable executable did not launch');
    browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`);const page=browser.contexts()[0].pages()[0];await page.locator('#start').waitFor();
    assert.equal(await page.evaluate(()=>typeof window.desktop.save),'function');
    await page.locator('#task-course').fill('模电');await page.locator('#task-input').fill('便携版启动验证');await page.locator('.task-amount summary').click();await page.locator('#task-amount').fill('3');await page.locator('#task-unit').fill('页');await page.locator('#task-form .add-button').click();await page.locator('[data-use-task]').click();await page.locator('#quick-resume').click();assert.equal(await page.locator('#timer').innerText(),'05:00');await page.waitForTimeout(1200);await page.locator('#finish').click();await page.locator('#confirm-yes').click();await page.locator('#review-actual').fill('2');await page.locator('#review-next-step').fill('从第 18 页继续');await page.locator('#review-skip').click();await page.evaluate(()=>window.prepareToClose());
    const data=JSON.parse(await fs.readFile(path.join(dataDir,'focus-data.json'),'utf8'));assert.equal(data.tasks[0].title,'便携版启动验证');assert.equal(data.tasks[0].course,'模电');assert.equal(data.sessions[0].course,'模电');assert.equal(data.sessions[0].nextStep,'从第 18 页继续');assert.equal(data.draft.title,'从第 18 页继续');assert.equal(data.sessions[0].quantity.actual,2);await page.locator('[data-page="calendar"]').first().click();await page.locator('#calendar-add').click();await page.locator('#event-title').fill('便携版日历验证');const date=await page.locator('#event-date').inputValue();await page.locator('#event-deadline').fill(date+'T23:59');await page.locator('[data-event-icon="📝"]').click();await page.locator('#event-form .primary').click();await page.locator('#event-dialog').waitFor({state:'hidden'});await page.evaluate(()=>window.prepareToClose());assert.equal(JSON.parse(await fs.readFile(path.join(dataDir,'focus-data.json'),'utf8')).events[0].title,'便携版日历验证');await page.reload();await page.locator('[data-page="calendar"]').first().click();assert.match(await page.locator('#calendar-agenda').innerText(),/便携版日历验证/);await page.locator('[data-page="focus"]').first().click();
    const miniCreated=browser.contexts()[0].waitForEvent('page');await page.locator('#show-mini').click();const mini=await miniCreated;await mini.locator('#capture').click();await mini.locator('#capture-input').fill('便携版小窗念头');await mini.locator('.save').click();await mini.locator('#capture-form').waitFor({state:'hidden'});await page.evaluate(()=>window.prepareToClose());const newData=JSON.parse(await fs.readFile(path.join(dataDir,'focus-data.json'),'utf8'));assert.equal(newData.thoughts[0].text,'便携版小窗念头');const webPath=decodeURIComponent(new URL(page.url()).pathname).replace(/^\/(?=[A-Za-z]:)/,'');const helper=path.resolve(path.dirname(webPath),'../desktop/window-focus.ps1').replace('app.asar'+path.sep,'app.asar.unpacked'+path.sep);assert.ok((await fs.stat(helper)).isFile());assert.ok((await page.evaluate(()=>window.desktop.backups())).length>0);await mini.screenshot({path:path.join(root,'test-results/portable-floating.png')});const log=await fs.readFile(path.join(dataDir,'startup.log'),'utf8');assert.ok(log.includes('"hardwareAcceleration":false'));assert.ok(!log.includes('process-gone'));
    await page.locator('.timer-tools [data-page="quick"]').click();await page.locator('#preset-add').click();await page.locator('#preset-title').fill('便携版固定阅读');await page.locator('#preset-minutes').fill('7');await page.locator('#preset-course').fill('模电');await page.locator('#preset-quantity summary').click();await page.locator('#preset-target').fill('3');await page.locator('#preset-unit').fill('页');await page.locator('#preset-form .primary').click();await page.locator('#preset-dialog').waitFor({state:'hidden'});await page.locator('#preset-list [data-start-preset]').click();assert.equal(await page.locator('#timer').innerText(),'07:00');await page.waitForTimeout(1200);await page.locator('#finish').click();await page.locator('#confirm-yes').click();await page.locator('#review-actual').fill('1');await page.locator('#review-skip').click();await page.evaluate(()=>window.prepareToClose());const presetData=JSON.parse(await fs.readFile(path.join(dataDir,'focus-data.json'),'utf8'));assert.equal(presetData.focusPresets[0].minutes,7);assert.equal(presetData.sessions.at(-1).title,'便携版固定阅读');assert.equal(presetData.sessions.at(-1).quantity.actual,1);await page.reload();assert.match(await page.locator('#quick-focus-list').innerText(),/便携版固定阅读/);
    await page.locator('[data-page="growth"]').first().click();await page.locator('#analysis-trend-svg').waitFor();assert.equal(await page.locator('.analysis-card').count(),4);await page.locator('#analysis-period').selectOption('7');assert.equal(await page.locator('#analysis-trend .analysis-data tbody tr').count(),7);assert.match(await page.locator('#analysis-courses').innerText(),/模电/);assert.match(await page.locator('#analysis-quantity').innerText(),/实际/);await page.locator('#growth-analysis').screenshot({path:path.join(root,'test-results/growth-portable.png')});await page.locator('[data-page="focus"]').first().click();
    const pref=await page.evaluate(()=>window.desktop.preferences());assert.equal(pref.quick,'Control+Alt+Q');assert.equal(pref.registrations.quick,true);const latest=await page.evaluate(()=>window.desktop.load());const reminderEvent={...latest.events[0],id:'portable-reminder-test',date:date,endDate:date,time:'',deadline:date+'T00:00',done:false,reminder:{anchor:'deadline',minutes:0}};const current=Date.now();const d=new Date(current);const pad=n=>String(n).padStart(2,'0');reminderEvent.date=reminderEvent.endDate=d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());reminderEvent.deadline=reminderEvent.date+'T'+pad(d.getHours())+':'+pad(d.getMinutes());await page.evaluate(e=>window.desktop.calendarSchedule([e]),reminderEvent);await page.evaluate(id=>window.desktop.calendarSnooze(id),reminderEvent.id);const reminderFile=JSON.parse(await fs.readFile(path.join(dataDir,'calendar-reminders.json'),'utf8'));const key=Object.keys(reminderFile).find(k=>k.startsWith(reminderEvent.id+':'));assert.ok(reminderFile[key]>current+590000);await page.evaluate(()=>window.desktop.calendarSchedule([]));assert.deepEqual(JSON.parse(await fs.readFile(path.join(dataDir,'calendar-reminders.json'),'utf8')),{});
    const closed=page.waitForEvent('close');await page.evaluate(()=>window.close()).catch(()=>{});await closed;
    console.log('PASS: final portable EXE extracts, launches, renders, starts a five-minute course goal, persists its record/next step, opens its real mini window, saves a captured thought, includes the native focus helper, persists learning quantity and calendar DDL through reload, starts and persists a reusable seven-minute preset, creates backups and closes; software rendering enabled.');
  }finally{await browser?.close();if(proc.exitCode===null)proc.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
