import test from 'node:test';import assert from 'node:assert/strict';
import {defaultState,validateState,elapsed,dayKey} from '../web/core.mjs';import {reachGoal,extendFocus,timerView,rememberHabit,recycle,recover} from '../web/workflow.mjs';import {SyncTracker} from '../web/sync.mjs';
const active=()=>({id:'focus',kind:'focus',title:'读一页',course:'模电',duration:1,elapsed:0,anchor:0,running:true});
test('goal arrival pauses once without creating a session; waiting does not accumulate time',()=>{const a=reachGoal(active(),61000);assert.equal(a.waiting,true);assert.equal(a.running,false);assert.equal(elapsed(a,600000),60000);assert.equal(timerView(a).text,'00:00');const s=defaultState();s.active=a;assert.doesNotThrow(()=>validateState(s));});
test('five-minute extension resumes from saved progress and respects the 120-minute limit',()=>{const a=extendFocus(reachGoal(active(),61000),5,false,120000);assert.equal(a.duration,6);assert.equal(a.goalDuration,1);assert.equal(timerView(a,15,120000).text,'05:00');assert.equal(elapsed(a,180000),120000);assert.throws(()=>extendFocus({...a,duration:120},5));});
test('paragraph finish counts additional work and handles subsequent pauses',()=>{const a=extendFocus(reachGoal(active(),61000),30,true,120000);assert.equal(timerView(a,15,180000).text,'+01:00');assert.equal(elapsed({...a,running:false,elapsed:120000},900000),120000);});
test('habit updates are atomic, use stable course IDs and merge between devices',()=>{const a=defaultState(),b=defaultState();const fields={course:' 模电 ',minutes:25,material:'https://example.com/textbook',position:'第 18 页'};rememberHabit(a,fields);rememberHabit(b,{...fields,minutes:15});assert.equal(a.courseHabits[0].id,b.courseHabits[0].id);const before=structuredClone(a);assert.throws(()=>rememberHabit(a,{...fields,minutes:NaN}));assert.deepEqual(a,before);const ta=new SyncTracker(a,'a'),tb=new SyncTracker(b,'b');ta.merge([tb.packet()]);const merged=ta.apply(a);assert.equal(merged.courseHabits.length,1);assert.equal(merged.courseHabits[0].position,'第 18 页');});
test('deletion and recovery round-trip locally, and a restored record beats a cloud tombstone',()=>{const s=defaultState();s.tasks=[{id:'t',title:'练习',done:false}];const tracker=new SyncTracker(s,'local');recycle(s,'tasks','t');tracker.observe(s);assert.equal(s.tasks.length,0);assert.equal(s.trash.length,1);assert.ok(!JSON.stringify(tracker.packet()).includes('deleted'));recover(s,s.trash[0].id);tracker.observe(s);assert.equal(tracker.apply(defaultState()).tasks[0].title,'练习');assert.equal(s.trash.length,0);});
test('questions and course habits accept old backups and reject corrupt values',()=>{const s=defaultState(),ended=Date.now();s.sessions=[{id:'s',title:'学过',seconds:60,note:'',ended,day:dayKey(ended),completed:true,question:'为什么？',questionResolved:false,position:'18 页'}];assert.doesNotThrow(()=>validateState(s));assert.throws(()=>validateState({...s,sessions:[{...s.sessions[0],questionResolved:1}]}));assert.throws(()=>validateState({...s,courseHabits:[{id:'x',course:'',minutes:15,material:'',position:'',updated:1}]}));});
