const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),{spawn}=require('node:child_process');
(async()=>{
 const root=path.resolve(__dirname,'..'),server=spawn(process.execPath,[path.join(root,'scripts/serve.cjs')],{windowsHide:true,stdio:'pipe'});let browser;
 try{
  await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error('Preview server exited '+code))); });
  browser=await chromium.launch({channel:'msedge',headless:true});const page=await browser.newPage({viewport:{width:1280,height:960}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto('http://127.0.0.1:4173');await page.locator('#start').waitFor();
  const stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('yiyu-focus-v1')));
  await page.locator('#focus-course').fill('模电');await page.locator('#edit-habit').click();await page.locator('#habit-minutes').fill('1');await page.locator('#habit-material').fill('https://example.com/course');await page.locator('#habit-position').fill('第 18 页');await page.locator('#habit-form .primary').click();assert.equal(await page.locator('#timer').innerText(),'01:00');assert.match(await page.locator('#course-position').innerText(),/18/);assert.equal((await stored()).courseHabits[0].minutes,1);
  await page.locator('#intention').fill('读懂虚短');await page.locator('#start').click();await page.clock.fastForward(61000);await page.locator('#soft-end').waitFor({state:'visible'});assert.equal(await page.locator('#review-dialog').isVisible(),false);assert.equal((await stored()).sessions.length,0);assert.equal((await stored()).active.waiting,true);
  await page.clock.fastForward(60000);await page.locator('#soft-extend').click();assert.equal(await page.locator('#timer').innerText(),'05:00');await page.clock.fastForward(301000);await page.locator('#soft-paragraph').click();await page.clock.runFor(11000);assert.match(await page.locator('#timer').innerText(),/^\+05:1/);
  await page.screenshot({path:path.join(root,'test-results/workflow-focus.png'),fullPage:true});await page.locator('#finish').click();await page.locator('#confirm-yes').click();await page.locator('#review-dialog details summary').click();await page.locator('#review-question').fill('<img src=x onerror=alert(1)> 为什么可以虚短？');await page.locator('#review-position').fill('第 20 页');await page.locator('#review-next-step').fill('做第一题');await page.locator('#review-note').fill('理解了负反馈的条件');await page.screenshot({path:path.join(root,'test-results/workflow-review.png')});await page.locator('#review-skip').click();
  const data=await stored();assert.equal(data.sessions.length,1);assert.ok(data.sessions[0].seconds>=370&&data.sessions[0].seconds<375);assert.equal(data.sessions[0].completed,true);assert.equal(data.courseHabits[0].position,'第 20 页');assert.equal(data.courseHabits[0].minutes,1);assert.equal(data.courseHabits[0].material,'https://example.com/course');
  await page.locator('[data-page="growth"]').first().click();assert.match(await page.locator('#week-questions').innerText(),/虚短/);await page.locator('[data-page="history"]').first().click();await page.locator('#unresolved-only').check();assert.equal(await page.locator('#history-list .record').count(),1);assert.equal(await page.locator('#history-list img').count(),0);await page.locator('[data-resolve-question]').click();await page.waitForFunction(()=>document.querySelectorAll('#history-list .record').length===0);await page.locator('#unresolved-only').uncheck();assert.match(await page.locator('.record-question').innerText(),/已解决/);await page.locator('[data-resolve-question]').click();await page.locator('[data-delete-session]').click();await page.locator('#confirm-yes').click();await page.waitForFunction(()=>document.querySelectorAll('#history-list .record').length===0);
  await page.locator('[data-page="settings"]').first().click();assert.match(await page.locator('#recycle-bin').innerText(),/读懂虚短/);await page.locator('[data-recover]').click();await page.waitForFunction(()=>!document.querySelector('[data-recover]'));await page.locator('[data-page="history"]').first().click();assert.equal(await page.locator('#history-list .record').count(),1);assert.match(await page.locator('.record-question').innerText(),/待解决/);
  await page.locator('[data-page="focus"]').first().click();await page.locator('#task-input').fill('可恢复的目标');await page.locator('#task-form .add-button').click();await page.locator('[data-delete-task]').click();await page.locator('#confirm-yes').click();await page.locator('[data-page="settings"]').first().click();await page.locator('[data-recover]').click();await page.locator('[data-page="focus"]').first().click();assert.match(await page.locator('#task-list').innerText(),/可恢复/);
  await page.locator('[data-page="inbox"]').first().click();await page.locator('#thought-input').fill('想查资料');await page.locator('#thought-form .primary').click();await page.locator('[data-delete-thought]').click();await page.locator('#confirm-yes').click();await page.locator('[data-page="settings"]').first().click();await page.locator('[data-recover]').click();await page.locator('[data-page="inbox"]').first().click();assert.match(await page.locator('#thought-list').innerText(),/想查资料/);
  await page.reload();await page.locator('#start').waitFor();assert.equal(await page.locator('#timer').innerText(),'01:00');await page.locator('#focus-course').fill('模电');await page.locator('#focus-course').dispatchEvent('change');assert.equal(await page.locator('#timer').innerText(),'01:00');assert.match(await page.locator('#course-position').innerText(),/20/);await page.setViewportSize({width:390,height:844});await page.locator('[data-page="history"]').first().click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
  console.log('PASS: course habits and material/position reload, soft expiry without modal or premature record, paused waiting excluded, extension/count-up, question resolve/filter/week, all three recycle/restore flows and escaped text.');
 }finally{await browser?.close();server.kill();}
})().catch(e=>{console.error(e);process.exitCode=1;});
