package local.yiyu.focus;
import android.app.*;import android.content.*;import android.os.Bundle;import java.io.*;import java.util.*;import org.json.*;import okhttp3.*;
public final class NativeChecks extends Instrumentation {
 @Override public void onCreate(Bundle args){super.onCreate(args);start();}
 void check(boolean condition,String message){if(!condition)throw new AssertionError(message);}
 JSONObject state()throws Exception{return new JSONObject().put("version",1).put("profile",new JSONObject().put("name","测试")).put("tasks",new JSONArray()).put("sessions",new JSONArray()).put("thoughts",new JSONArray()).put("active",JSONObject.NULL);}
 JSONObject packet(String name)throws Exception{return new JSONObject().put("version",1).put("entries",new JSONArray().put(new JSONObject().put("group","profile").put("id","name").put("value",name).put("clock",new JSONObject().put("time",1).put("device","test"))));}
 @Override public void onStart(){Bundle result=new Bundle();try{
  check(!Reminders.changedBoot(7,7)&&Reminders.changedBoot(7,8)&&!Reminders.changedBoot(-1,8),"boot delivery confused with reboot");
  File folder=new File(getTargetContext().getFilesDir(),"native-checks-"+System.currentTimeMillis());if(!folder.mkdirs())throw new IOException("test folder");Context isolated=new ContextWrapper(getTargetContext()){@Override public File getFilesDir(){return folder;}};StateStore data=new StateStore(isolated);JSONObject s=state();data.save(s);s.getJSONArray("tasks").put(new JSONObject().put("id","t").put("title","恢复前记录"));data.save(s);check(data.list().length()==1,"checkpoint multiplied backups");String backup=data.snapshot(s,"手动备份");s.getJSONArray("tasks").put(new JSONObject().put("id","new").put("title","新版记录"));data.save(s);data.restore(data.backup(backup));check(data.load().getJSONArray("tasks").length()==1,"restore data changed");boolean protectedOld=false;JSONArray rows=data.list();for(int i=0;i<rows.length();i++){JSONObject row=rows.getJSONObject(i);if(row.optString("reason").equals("恢复前保护"))protectedOld=data.backup(row.getString("id")).getJSONArray("tasks").length()==2;}check(protectedOld,"restore did not protect original");
  File original=new File(folder,"focus-data.json");try(FileWriter writer=new FileWriter(original)){writer.write("{corrupt-original");}boolean blocked=false;try{data.load();}catch(Exception e){blocked=true;}check(blocked,"corrupt data accepted");blocked=false;try{data.save(s);}catch(Exception e){blocked=true;}check(blocked,"corrupt data overwritten");data.restore(data.backup(backup));check(Arrays.stream(folder.list()).anyMatch(n->n.startsWith("focus-data-corrupt-")),"corrupt original not preserved");for(int i=0;i<32;i++)data.snapshot(s,"测试轮转");check(data.list().length()==30,"backup retention unbounded");blocked=false;try{data.backup("../focus-data");}catch(Exception e){blocked=true;}check(blocked,"backup path traversal accepted");
  Credentials credentials=new Credentials(isolated);JSONObject auth=new JSONObject().put("username","test@example.com").put("password","NOT-REAL-native-test-password");credentials.save(auth);check(!StateStore.read(new File(folder,"sync-credentials.enc"),8192).contains(auth.getString("password")),"credentials stored plaintext");check(credentials.load().getString("password").equals(auth.getString("password")),"keystore round trip failed");credentials.clear();check(credentials.load()==null,"disconnect left credentials");
  FakeCloud cloud=new FakeCloud();Nutstore client=new Nutstore(auth,new OkHttpClient.Builder().addInterceptor(cloud).build());client.connect();check(client.read().length()==0,"empty cloud has records");String device="11111111-1111-4111-8111-111111111111";JSONObject p=packet("中文昵称");check(client.write(device,p),"first upload failed");check("*".equals(cloud.lastCondition),"first upload may replace existing file");check(client.read().length()==1,"read/merge file missing");int gets=cloud.gets;client.read();check(cloud.gets==gets,"ETag cache ignored");cloud.foreign=true;check(client.read().length()==1,"foreign origin accepted");cloud.files.put("22222222-2222-4222-8222-222222222222.json",packet("另一台设备").toString());cloud.tags.put("22222222-2222-4222-8222-222222222222.json","remote");check(client.read().length()==2,"second device file missing");cloud.conflict=true;blocked=false;try{client.write(device,packet("后来修改"));}catch(IOException e){blocked=e.getMessage().contains("变化");}check(blocked,"conditional conflict overwritten");cloud.conflict=false;cloud.entity=true;blocked=false;try{client.read();}catch(IOException e){blocked=true;}check(blocked,"external XML entity accepted");cloud.entity=false;cloud.offline=true;blocked=false;try{client.read();}catch(IOException e){blocked=e.getMessage().contains("本机");}check(blocked,"network failure claimed success");
  result.putString("stream","PASS: native atomic storage, 30 rolling backups, protected restore, corrupt-file preservation, path guard, Android Keystore credentials, fixed-origin WebDAV, UTF-8, ETag cache, multi-device files, conditional write conflict, XML entity rejection and offline errors.\n");finish(Activity.RESULT_OK,result);
 }catch(Throwable e){StringWriter text=new StringWriter();e.printStackTrace(new PrintWriter(text));result.putString("stream",text.toString());finish(Activity.RESULT_CANCELED,result);}}
 static final class FakeCloud implements Interceptor {final Map<String,String> files=new HashMap<>(),tags=new HashMap<>();int gets,writes;String lastCondition;boolean foreign,entity,conflict,offline;
  @Override public Response intercept(Chain chain)throws IOException{Request req=chain.request();if(!req.url().toString().startsWith(Nutstore.BASE))throw new IOException("foreign request");if(offline)throw new IOException("offline");String name=req.url().pathSegments().get(req.url().pathSegments().size()-1),body="",tag="";int status=200;switch(req.method()){
   case "MKCOL":status=201;break;
   case "PROPFIND":StringBuilder xml=new StringBuilder("<d:multistatus xmlns:d=\"DAV:\">");for(String f:files.keySet())xml.append("<d:response><d:href>/dav/YiyuFocus/").append(f).append("</d:href><d:propstat><d:prop><d:getetag>\"").append(tags.get(f)).append("\"</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response>");if(foreign)xml.append("<d:response><d:href>https://evil.example/dav/YiyuFocus/33333333-3333-4333-8333-333333333333.json</d:href><d:propstat><d:prop><d:getetag>evil</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response>");xml.append("</d:multistatus>");body=(entity?"<!DOCTYPE x [<!ENTITY x SYSTEM 'file:///system/build.prop'>]>":"")+xml;status=207;break;
   case "GET":gets++;body=files.get(name);tag="\""+tags.get(name)+"\"";break;
   case "PUT":lastCondition=req.header("If-None-Match");if(lastCondition==null)lastCondition=req.header("If-Match");if(conflict){status=412;break;}okio.Buffer bytes=new okio.Buffer();req.body().writeTo(bytes);files.put(name,bytes.readUtf8());tags.put(name,"v"+(++writes));tag="\""+tags.get(name)+"\"";status=201;break;
   default:throw new IOException("unexpected method");
  }Response.Builder out=new Response.Builder().request(req).protocol(Protocol.HTTP_1_1).code(status).message("test").body(ResponseBody.create(body,MediaType.parse("text/plain")));if(!tag.isEmpty())out.header("ETag",tag);return out.build();
  }
 }
}
