import {eventProgress} from './journey.mjs';
import {dayKey} from './core.mjs';
import {eventIcons,monthDays,shiftMonth,eventsOnDay,deadlineLabel,validEvent} from './planning.mjs';
export function setupCalendar({getState,save,renderAll,toast,confirmAction,recycle,startEvent,escape}){
 const $=s=>document.querySelector(s);let selected=dayKey(),month=selected.slice(0,7),editing=null,chosenIcon='📚',saving=false;
 const when=e=>e.date+(e.time?' '+e.time:' · 全天')+(e.endDate!==e.date?' — '+e.endDate:'')+(e.endTime?' — '+e.endTime:'');
 function item(e){const progress=eventProgress(getState(),e);const progressHTML='<div class="calendar-item-progress">已投入 '+Math.floor(progress.seconds/60)+' 分钟 · '+progress.count+' 次专注'+progress.quantities.map(q=>' · '+escape(q.actual+' '+q.unit)).join('')+(progress.nextStep?'<br>下一步：'+escape(progress.nextStep):'')+'</div>';const overdue=e.deadline&&!e.done&&+new Date(e.deadline)<Date.now();return '<div class="calendar-item '+(e.done?'done':'')+'"><span class="calendar-item-icon" aria-hidden="true">'+escape(e.icon)+'</span><div class="calendar-item-body"><button class="calendar-item-title" data-event-edit="'+escape(e.id)+'">'+escape(e.title)+'</button><small>'+escape(when(e))+'</small>'+(e.course?'<small>'+escape(e.course)+'</small>':'')+(e.deadline?'<small>DDL '+escape(e.deadline.replace('T',' '))+'</small><span data-deadline-id="'+escape(e.id)+'" class="deadline-badge '+(overdue?'overdue':'')+'">'+escape(deadlineLabel(e))+'</span>':'')+(e.notes?'<p>'+escape(e.notes)+'</p>':'')+progressHTML+'<div class="calendar-item-actions"><button class="text-button" data-event-done="'+escape(e.id)+'">'+(e.done?'重新打开':'标记完成')+'</button><button class="text-button" data-event-focus="'+escape(e.id)+'">开始专注</button><button class="text-button" data-event-delete="'+escape(e.id)+'">删除</button></div></div></div>';}
 function render(){const events=getState().events||[];$('#calendar-month').textContent=Number(month.slice(0,4))+' 年 '+Number(month.slice(5))+' 月';$('#calendar-day-title').textContent=selected===dayKey()?'今天的安排':selected+' 的安排';$('#calendar-grid').innerHTML=monthDays(month).map(date=>{const rows=eventsOnDay(events,date);return '<button class="calendar-cell '+(date.slice(0,7)!==month?'outside ':'')+(date===dayKey()?'today':'')+'" data-calendar-date="'+date+'" aria-pressed="'+(date===selected)+'" aria-label="'+date+'，'+rows.length+' 项安排"><span class="day-number">'+Number(date.slice(8))+'</span><span class="calendar-marks" aria-hidden="true">'+rows.slice(0,2).map(e=>escape(e.icon)).join('')+(rows.length>2?' +':'')+(rows.some(e=>!e.done&&e.deadline?.slice(0,10)===date)?'<i class="ddl-dot"></i>':'')+'</span></button>';}).join('');const rows=eventsOnDay(events,selected);$('#calendar-agenda').innerHTML=rows.length?rows.map(item).join(''):'<p class="muted">这一天还没有安排。留白，或放一件重要的事。</p>';const deadlines=events.filter(e=>e.deadline&&!e.done).sort((a,b)=>a.deadline.localeCompare(b.deadline));$('#calendar-deadlines').innerHTML=deadlines.length?deadlines.map(item).join(''):'<p class="muted">没有待完成的截止日期。</p>';}
 function renderIcons(){ $('#event-icons').innerHTML=eventIcons.map(([value,label])=>'<button type="button" data-event-icon="'+escape(value)+'" aria-label="'+label+'图标" aria-pressed="'+(value===chosenIcon)+'">'+value+'</button>').join('');}
 function open(event=null){editing=event?.id||null;chosenIcon=event?.icon||'📚';$('#event-dialog-title').textContent=event?'编辑安排':'新建安排';for(const [field,value] of Object.entries({title:event?.title||'',date:event?.date||selected,'end-date':event?.endDate||selected,time:event?.time||'','end-time':event?.endTime||'',deadline:event?.deadline||'',course:event?.course||'',notes:event?.notes||''}))$('#event-'+field).value=value;$('#event-done').checked=!!event?.done;$('#event-focus-minutes').value=event?.focusMinutes||getState().profile.duration;$('#event-target').value=event?.quantity?.target??'';$('#event-unit').value=event?.quantity?.unit||'页';$('#event-quantity').open=!!event?.quantity;$('#event-reminder-anchor').value=event?.reminder?.anchor||'off';const offset=event?.reminder?.minutes??60;$('#event-reminder-offset').value=[0,60,1440].includes(offset)?String(offset):'custom';$('#event-reminder-minutes').value=offset;$('#event-custom-reminder').hidden=$('#event-reminder-offset').value!=='custom';$('#event-error').hidden=true;renderIcons();$('#event-dialog').showModal();$('#event-title').focus();}
 $('#calendar-add').onclick=()=>open();$('#calendar-day-add').onclick=()=>open();
 $('#calendar-prev').onclick=()=>{const next=shiftMonth(month,-1);if(Number(next.slice(0,4))>=1970){month=next;render();}};$('#calendar-next').onclick=()=>{const next=shiftMonth(month,1);if(Number(next.slice(0,4))<=2199){month=next;render();}};$('#calendar-today').onclick=()=>{selected=dayKey();month=selected.slice(0,7);render();};
 $('#calendar-grid').onclick=e=>{const button=e.target.closest('[data-calendar-date]');if(button){selected=button.dataset.calendarDate;month=selected.slice(0,7);render();}};
 $('#calendar-grid').onkeydown=e=>{const button=e.target.closest('[data-calendar-date]');const deltas={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7};if(!button||!(e.key in deltas))return;e.preventDefault();const date=new Date(button.dataset.calendarDate+'T12:00:00');date.setDate(date.getDate()+deltas[e.key]);if(date.getFullYear()<1970||date.getFullYear()>2199)return;selected=dayKey(date);month=selected.slice(0,7);render();$('#calendar-grid [data-calendar-date="'+selected+'"]').focus();};
 $('#event-icons').onclick=e=>{const button=e.target.closest('[data-event-icon]');if(button){chosenIcon=button.dataset.eventIcon;renderIcons();$('#event-icons [data-event-icon="'+chosenIcon+'"]').focus();}};
 $('#event-reminder-offset').onchange=()=>$('#event-custom-reminder').hidden=$('#event-reminder-offset').value!=='custom';
 $('#event-date').onchange=()=>{if($('#event-end-date').value<$('#event-date').value)$('#event-end-date').value=$('#event-date').value;};
 $('#event-form').onsubmit=async e=>{e.preventDefault();if(saving)return;const state=getState(),old=(state.events||[]).find(e=>e.id===editing),now=Date.now();if(editing&&!old){toast('这项安排已在其他设备删除，请重新新建。');return;}const event={id:editing||crypto.randomUUID(),title:$('#event-title').value.trim(),icon:chosenIcon,date:$('#event-date').value,endDate:$('#event-end-date').value,time:$('#event-time').value,endTime:$('#event-end-time').value,deadline:$('#event-deadline').value,course:$('#event-course').value.trim(),notes:$('#event-notes').value.trim(),done:$('#event-done').checked,focusMinutes:Number($('#event-focus-minutes').value),...($('#event-target').value?{quantity:{target:Number($('#event-target').value),unit:$('#event-unit').value.trim()}}:{}),...($('#event-reminder-anchor').value!=='off'?{reminder:{anchor:$('#event-reminder-anchor').value,minutes:Number($('#event-reminder-offset').value==='custom'?$('#event-reminder-minutes').value:$('#event-reminder-offset').value)}}:{}),created:old?.created||now,updated:now};if(!validEvent(event)){$('#event-error').textContent='请检查日期与时间：结束不能早于开始，结束时间需要填写开始时间；DDL 提醒需要截止日期，学习量和提醒分钟也需有效。';$('#event-error').hidden=false;return;}saving=true;const submit=$('#event-form .primary');submit.disabled=true;state.events??=[];const before=structuredClone(state.events);if(old)state.events[state.events.indexOf(old)]=event;else state.events.push(event);try{await save();selected=event.date;month=selected.slice(0,7);$('#event-dialog').close();renderAll();toast('安排已保存。');}catch(error){state.events=before;toast('安排保存失败：'+error.message);}finally{saving=false;submit.disabled=false;}};
 async function action(e){const button=e.target.closest('button');if(!button)return;const state=getState(),event=(state.events||[]).find(row=>row.id===(button.dataset.eventEdit||button.dataset.eventDone||button.dataset.eventDelete||button.dataset.eventFocus));if(!event)return;if(button.dataset.eventEdit){open(event);return;}if(button.dataset.eventFocus){if(state.active){toast('先完成当前这一段，再切换目标。');return;}startEvent(event);return;}if(button.dataset.eventDelete&&!await confirmAction('把这项安排移入回收站？','30 天内可在偏好中恢复；删除也会随账号同步。'))return;const events=structuredClone(state.events),trash=structuredClone(state.trash||[]);if(button.dataset.eventDone){event.done=!event.done;event.updated=Date.now();}else recycle(state,'events',event.id);try{await save();renderAll();}catch(error){state.events=events;state.trash=trash;toast('保存失败：'+error.message);renderAll();}}
 $('#calendar-agenda').onclick=action;$('#calendar-deadlines').onclick=action;let lastMinute=-1;function refresh(){const minute=Math.floor(Date.now()/60000);if(minute===lastMinute)return;lastMinute=minute;for(const badge of document.querySelectorAll('[data-deadline-id]')){const event=(getState().events||[]).find(e=>e.id===badge.dataset.deadlineId);if(event){badge.textContent=deadlineLabel(event);badge.classList.toggle('overdue',!event.done&&+new Date(event.deadline)<Date.now());}}}return {render,refresh,show:eventId=>{const e=(getState().events||[]).find(e=>e.id===eventId);if(e){selected=e.date;month=selected.slice(0,7);render();}}};
}
