import {manualSession} from './time-records.mjs';
const $=s=>document.querySelector(s);
const link=document.createElement('link');link.rel='stylesheet';link.href='improvements.css';document.head.append(link);
$('.timer-card .card-top').insertAdjacentHTML('afterend','<div class="zen-cue"><strong id="zen-target"></strong><p id="zen-position"></p></div>');
$('#history-search').insertAdjacentHTML('beforebegin','<button id="history-add" class="secondary">＋ 补记专注</button>');
$('#page-focus .focus-layout').insertAdjacentHTML('afterend','<article id="relay-card" class="relay-card"><div class="card-top"><h2>跨设备接着学</h2><button id="relay-refresh" class="text-button">刷新接力</button></div><p id="relay-status" class="muted">连接同一坚果云账号后，可暂停这一段并交给另一台设备。</p><div class="relay-actions"><button id="relay-send" class="secondary">暂停并发送接力</button><button id="relay-cancel" class="secondary" hidden>撤回接力</button></div><div id="relay-list"></div></article>');
$('.motion-setting').insertAdjacentHTML('beforebegin','<form id="interface-preferences" class="settings-card"><h2>专注时，少一点干扰</h2><label class="checkbox-label"><input id="auto-zen" type="checkbox">开始专注时自动进入沉浸界面</label><label>达到每日目标或个人里程碑时<select id="celebration-mode"><option value="leaf">轻微叶子动效</option><option value="confetti">彩纸礼炮</option><option value="off">关闭完成反馈</option></select></label><p class="micro-copy">同一里程碑只提醒一次。补记和云端同步不触发；遵循减少动画设置。界面偏好仅在当前设备生效。</p><button class="primary">保存界面偏好</button><button id="celebration-preview" class="secondary" type="button">预览反馈</button></form>');
$('#event-focus-minutes').closest('.event-fields').insertAdjacentHTML('beforebegin','<div class="event-fields"><label>重复安排<select id="event-repeat"><option value="off">不重复</option><option value="daily">每天</option><option value="weekdays">工作日（周一至周五）</option><option value="weekly">每周指定日期</option></select></label><label id="event-repeat-until-label" hidden>重复到<input id="event-repeat-until" type="date" min="1970-01-01" max="2199-12-31"></label></div><fieldset id="event-repeat-days" hidden><legend>选择星期</legend>'+['一','二','三','四','五','六','日'].map((v,i)=>'<label><input type="checkbox" value="'+(i+1)+'">周'+v+'</label>').join('')+'</fieldset><label id="event-scope-label" hidden>本次修改范围<select id="event-scope"><option value="single">仅这一次</option><option value="future">这次及后续安排</option></select></label><p id="event-repeat-help" class="micro-copy" hidden>按本地日期生成到所选结束日（最多一年），每次可独立完成、专注与提醒。修改重复规则时请选择“这次及后续安排”。</p>');
document.body.insertAdjacentHTML('beforeend','<dialog id="record-editor" aria-labelledby="record-editor-title"><form id="record-editor-form"><h2 id="record-editor-title">补记一段专注</h2><label>目标<input id="record-title" maxlength="200" required></label><label>课程<input id="record-course" list="course-suggestions" maxlength="40"></label><div class="event-fields"><label>结束时间<input id="record-ended" type="datetime-local" step="1" required></label><label>实际专注（分钟）<input id="record-minutes" type="number" min="0.0166" max="120" step="any" required></label></div><label>收获<textarea id="record-note" maxlength="2000"></textarea></label><p id="record-original"></p><p class="micro-copy">修正后以结束时间向前分配时长，跨午夜分到两天；原始时长保留。含暂停的旧记录请填写实际专注时长。</p><p id="record-editor-error" class="event-error" role="alert" hidden></p><div class="dialog-actions"><button class="secondary" type="button" data-close="record-editor">取消</button><button class="primary">保存记录</button></div></form></dialog><dialog id="series-delete-dialog" aria-labelledby="series-delete-title"><h2 id="series-delete-title">删除重复安排</h2><p>只删除这一次，或这次及后续安排。此前的安排和专注记录保留。</p><div class="dialog-actions"><button id="series-delete-cancel" class="secondary">取消</button><button id="series-delete-one" class="secondary">仅这一次</button><button id="series-delete-future" class="primary">这次及后续</button></div></dialog><div id="completion-feedback" role="status" hidden></div>');
export function setupRecordEditor({getState,save,renderAll,toast}){
 let editing=null,busy=false;const local=t=>{const d=new Date(t);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')+':'+String(d.getSeconds()).padStart(2,'0');};
 function open(session=null){editing=session?.id||null;$('#record-editor-title').textContent=session?'修正这段记录':'补记一段专注';$('#record-title').value=session?.title||'';$('#record-course').value=session?.course||'';$('#record-ended').value=local(session?.ended||Date.now());$('#record-ended').max=local(Date.now());$('#record-minutes').value=session?Math.round(session.seconds/60*10000)/10000:15;$('#record-note').value=session?.note||'';$('#record-editor-error').hidden=true;$('#record-original').textContent=session?'原记录：'+session.seconds+' 秒 · '+new Date(session.ended).toLocaleString('zh-CN'):'补记会标明来源，计入统计，不触发完成庆祝。';$('#record-editor').showModal();$('#record-title').focus();}
 $('#history-add').onclick=()=>open();
 $('#record-editor-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const state=getState(),old=state.sessions.find(s=>s.id===editing);if(editing&&!old){toast('这条记录已删除，请重新补记。');return;}const before=structuredClone(state.sessions);try{const next=manualSession({title:$('#record-title').value,course:$('#record-course').value,ended:+new Date($('#record-ended').value),minutes:$('#record-minutes').value,note:$('#record-note').value},old);busy=true;$('#record-editor-form .primary').disabled=true;if(old)state.sessions[state.sessions.indexOf(old)]=next;else state.sessions.push(next);await save();$('#record-editor').close();renderAll();toast(old?'记录已修正，统计已更新。':'这一段已经补记。');}catch(error){state.sessions=before;$('#record-editor-error').textContent=error.message;$('#record-editor-error').hidden=false;}finally{busy=false;$('#record-editor-form .primary').disabled=false;}};
 return {open};
}
