export const dayKey = (time = Date.now()) => {
  const d = new Date(time);
  return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
};
export const eventIcons=[['📚','学习'],['✍️','作业'],['📝','考试'],['🎯','目标'],['💻','项目'],['🧪','实验'],['📅','安排'],['⏰','截止'],['🏃','运动'],['☕','休息'],['🎉','活动'],['📌','其他']];
export const focusIcons=[...eventIcons,...[["📖","阅读"],["🔤","单词"],["🎧","听力"],["🗣️","口语"],["🧠","记忆"],["🧮","数学"],["📓","笔记"],["🔍","研究"],["⌨️","编程"],["🔌","电路"],["🔬","科学"],["🔭","天文"],["🎨","绘画"],["🎹","钢琴"],["🎸","吉他"],["🎼","乐理"],["♟️","棋类"],["🧘","冥想"],["🚶","散步"],["🚴","骑行"],["🏋️","力量训练"],["🌱","习惯"],["💧","喝水"],["🗂️","整理"]]];
export function validDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(value+'T12:00:00');return Number.isFinite(+date)&&dayKey(date)===value&&Number(value.slice(0,4))>=1970&&Number(value.slice(0,4))<=2199;}
export const validTime=value=>typeof value==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value);
export const validDeadline=value=>typeof value==='string'&&value.length===16&&validDate(value.slice(0,10))&&value[10]==='T'&&validTime(value.slice(11));
export function validQuantity(q){return q===undefined||!!q&&Number.isFinite(q.target)&&q.target>0&&q.target<=1000000&&typeof q.unit==='string'&&q.unit.trim().length>0&&q.unit.length<=20&&(q.actual===undefined||Number.isFinite(q.actual)&&q.actual>=0&&q.actual<=1000000);}
export const validReminder=r=>r===undefined||!!r&&['start','deadline'].includes(r.anchor)&&Number.isInteger(r.minutes)&&r.minutes>=0&&r.minutes<=10080;
export function validEvent(e){return !!e&&(e.seriesId===undefined||typeof e.seriesId==='string'&&e.seriesId.length>0&&e.seriesId.length<=50)&&(e.repeat===undefined||!!e.seriesId&&e.repeat&&['daily','weekdays','weekly'].includes(e.repeat.kind)&&validDate(e.repeat.until)&&e.repeat.until>=e.date&&Array.isArray(e.repeat.days)&&e.repeat.days.length<=7&&e.repeat.days.every(d=>Number.isInteger(d)&&d>=1&&d<=7)&&new Set(e.repeat.days).size===e.repeat.days.length&&(e.repeat.kind!=='weekly'||e.repeat.days.length>0))&&validReminder(e.reminder)&&(!e.reminder||e.reminder.anchor!=='deadline'||!!e.deadline)&&(e.focusMinutes===undefined||Number.isInteger(e.focusMinutes)&&e.focusMinutes>=1&&e.focusMinutes<=120)&&validQuantity(e.quantity)&&e.quantity?.actual===undefined&&typeof e.id==='string'&&e.id.length>0&&e.id.length<=100&&typeof e.title==='string'&&e.title.trim().length>0&&e.title.length<=200&&eventIcons.some(([i])=>i===e.icon)&&validDate(e.date)&&validDate(e.endDate)&&e.endDate>=e.date&&(e.time===''||validTime(e.time))&&(e.endTime===''||validTime(e.endTime))&&(!e.endTime||!!e.time)&&(!e.time||!e.endTime||e.endDate>e.date||e.endTime>=e.time)&&(e.deadline===''||validDeadline(e.deadline))&&typeof e.course==='string'&&e.course.length<=40&&typeof e.notes==='string'&&e.notes.length<=2000&&typeof e.done==='boolean'&&Number.isFinite(e.created)&&e.created>=0&&e.created<=1e14&&Number.isFinite(e.updated)&&e.updated>=0&&e.updated<=1e14;}
export function monthDays(month){const start=new Date(month+'-01T12:00:00');start.setDate(1-(start.getDay()+6)%7);return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return dayKey(d);});}
export function shiftMonth(month,delta){const d=new Date(month+'-01T12:00:00');d.setMonth(d.getMonth()+delta);return dayKey(d).slice(0,7);}
export function eventsOnDay(events,date){return events.filter(e=>e.date<=date&&e.endDate>=date||e.deadline?.slice(0,10)===date).sort((a,b)=>Number(a.done)-Number(b.done)||(a.time||'').localeCompare(b.time||'')||a.created-b.created);}
export function deadlineLabel(e,now=Date.now()){if(!e.deadline)return '';if(e.done)return '已完成';const diff=+new Date(e.deadline)-now;if(diff<0)return '已过截止时间';if(diff<3600000)return '距 DDL '+Math.ceil(diff/60000)+' 分钟';if(diff<86400000)return '距 DDL '+Math.ceil(diff/3600000)+' 小时';return '距 DDL '+Math.ceil(diff/86400000)+' 天';}
export function quantityTotals(sessions){const map=new Map();for(const s of sessions){const q=s.quantity;if(q?.actual!==undefined)map.set(q.unit,(map.get(q.unit)||0)+q.actual);}return [...map].map(([unit,actual])=>({unit,actual:Math.round(actual*1000)/1000}));}
export const quantityLabel=q=>q?(q.actual===undefined?'目标 '+q.target+' '+q.unit:'完成 '+q.actual+' / '+q.target+' '+q.unit):'';

export function validPreset(p){return !!p&&(p.pinned===undefined||typeof p.pinned==='boolean')&&(p.order===undefined||Number.isFinite(p.order)&&p.order>=0&&p.order<=1e14)&&typeof p.id==='string'&&p.id.length>0&&p.id.length<=100&&typeof p.title==='string'&&p.title.trim().length>0&&p.title.length<=200&&focusIcons.some(([icon])=>icon===p.icon)&&typeof p.course==='string'&&p.course.length<=40&&Number.isInteger(p.minutes)&&p.minutes>=1&&p.minutes<=120&&validQuantity(p.quantity)&&p.quantity?.actual===undefined&&Number.isFinite(p.created)&&p.created>=0&&p.created<=1e14&&Number.isFinite(p.updated)&&p.updated>=0&&p.updated<=1e14;}
